---
- set_fact: omnisup_dir={{ install_prefix }}

- name: Get php-fpm version
  shell: php --version |head -1 | awk -F  "." '{print $1 "." $2}' | awk -F " " '{print $2}'
  register: command_result
  become: true
  become_method: sudo
  when: ansible_os_family == "Debian"

- set_fact: php_version={{ command_result.stdout }}
  when: ansible_os_family == "Debian"
- set_fact: phpfpm_path=/etc/php/{{ php_version }}/fpm/
  when: ansible_os_family == "Debian"

- file: path={{ install_prefix }}Omnisup state=absent

- name: Modify of php.ini (centos)
  lineinfile: dest=/etc/php.ini regexp="^;cgi.fix_pathinfo" line="cgi.fix_pathinfo=0"
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Modify of php.ini (debian)
  lineinfile: dest="{{ phpfpm_path }}php.ini"  regexp="^;cgi.fix_pathinfo" line="cgi.fix_pathinfo=0"
  become: true
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: Add php-fpm configuration for supervision
  template: src=templates/www.conf.j2 dest=/etc/php-fpm.d/www.conf
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Add php-fpm configuration for supervision
  template: "src=templates/www.conf.j2 dest={{ phpfpm_path }}pool.d/www.conf"
  become: true
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: Modify of config.js in /static/Js
  template: "src=templates/config.js.j2 dest={{ omnisup_dir }}ominicontacto/Omnisup/static/Js/config.js"

- name: Create simbolic link of Omnisup directory
  file: src={{ omnisup_dir }}/ominicontacto/Omnisup dest={{ omnisup_dir }}Omnisup state=link owner={{ usuario }} group={{ usuario }} mode=755

- name: Enable and start of php-fpm service
  service: name=php-fpm state=started enabled=yes
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Enable and start of php-fpm service
  service: name=php{{ php_version }}-fpm state=started enabled=yes
  become: true
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: Change permission of the php-fpm.sock (centos)
  file: path=/var/run/php-fpm/php-fpm.sock owner={{ usuario }} group={{ usuario }}
  when: ansible_os_family == "RedHat"

- name: Change permission of the php-fpm.sock (debian)
  file: path=/var/run/php/php{{ php_version }}-fpm.sock owner={{ usuario }} group={{ usuario }}
  when: ansible_os_family == "Debian"

- name: Set permissions of required to {{ usuario }}'s user
  file: path=/var/lib/nginx/ owner={{ usuario }} group={{ usuario }} state=directory
  become: true
  become_method: sudo

- name: Creation of /etc/nginx/conf.d/supervision.conf
  template: src=templates/supervision.conf.j2 dest=/etc/nginx/conf.d/supervision.conf
  become: true
  become_method: sudo

- name: Restart of nginx
  service: name=nginx state=restarted enabled=yes
  become: true
  become_method: sudo
