# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

version: '3.7'
services:
  asterisk:
    container_name: asterisk
    depends_on:
      - database
    hostname: asterisk
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/asterisk:de0.1
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.2
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - type: volume
        source: grabaciones
        target: /opt/omnileads/asterisk/var/spool/asterisk/monitor/
      - type: bind
        source: "$PWD/../../../ominicontacto_voip/asterisk-files/conf/"
        target: /var/tmp/astfiles/
    working_dir: /opt/omnileads/asterisk

  database:
    container_name: database
    hostname: database
    dns: 8.8.8.8
    environment:
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/database:de0.1
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.3
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/9.6/main/

  dialer:
    container_name: dialer
    hostname: dialer
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/dialer:de0.1
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.4
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

  kamailio:
    container_name: kamailio
    depends_on:
      - database
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    healthcheck:
      test: ["CMD-SHELL", "kamcmd -s /opt/omnileads/kamailio/run/kamailio/kamailio_ctl autheph.dump_secrets"]
      interval: 1m
      timeout: 10s
      start_period: 50s
      retries: 1
    hostname: kamailio
    image: freetechsolutions/kamailio:de0.1
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.5
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - type: bind
        source: "$PWD/../../../ominicontacto_voip/kamailio-files/"
        target: /var/tmp/kamfiles
    working_dir: /opt/omnileads/kamailio

  omniapp:
    container_name: omniapp
    hostname: omniapp
    depends_on:
      - database
    #  - asterisk
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/omniapp:de0.1
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.6
    privileged: true
    ports:
     - "443:443/tcp"
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - type: bind
        source: "$PWD/../../.."
        target: /opt/omnileads/ominicontacto/
      - type: volume
        source: grabaciones
        target: /opt/omnileads/asterisk/var/spool/asterisk/monitor
    working_dir: /opt/omnileads/ominicontacto

  pbx-emulator:
    container_name: pbx-emulator
    hostname: pbx-emulator
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/pbx-emulator:0.1
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.7
    ports:
      - 5060:5060
      - 10000-10020:10000-10020
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
volumes:
  grabaciones:
  ominicontacto:
  database:
