version: '3.7'
services:
  asterisk:
#    command:
#      - /sbin/init
    container_name: asterisk
    hostname: asterisk
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/base-ubuntu:latest
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.2
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

  database:
#    command:
#      - /sbin/init
    container_name: database
    hostname: database
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/base-ubuntu:latest
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.3
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

  dialer:
#    command:
#      - /sbin/init
    container_name: dialer
    hostname: dialer
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/base-ubuntu:latest
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.4
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

  kamailio:
#    command:
#      - /sbin/init
    container_name: kamailio
    hostname: kamailio
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
      - DOCKER_IP=172.19.0.6
    image: freetechsolutions/base-ubuntu:latest
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.5
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

  omniapp:
#    cap_add:
#      - SYS_ADMIN
#    command:
#      - /sbin/init
    container_name: omniapp
    hostname: omniapp
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/base-ubuntu:latest
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.6
    privileged: true
    ports:
     - "443:443/tcp"
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - type: bind
        source: "$PWD/../../.."
        target: /opt/omnileads/ominicontacto/

  pbx-emulator:
#    cap_add:
#      - SYS_ADMIN
#    command:
#      - /sbin/init
    container_name: pbx-emulator
    hostname: pbx-emulator
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/pbx-emulator:1.0
    logging:
      driver: syslog
    networks:
      devnet:
        ipv4_address: 172.16.0.7
    ports:
      - 5060:5060
      - 10000-10020:10000-10020
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
volumes:
  ominicontacto:
