# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Instalo paquetes de kamailio/rtpengine
- name: Installation of kamailio/rtpengine packages
  yum: name={{ item }} state=present
  with_items:
    - bison
    - bison-devel
    - expat
    - expat-devel
    - flex
    - gcc
    - gcc-c++
    - glib2-devel
    - hiredis
    - hiredis-devel
    - iptables-devel
    - iptables-services
    - json-glib-devel
    - libevent-devel
    - libpcap-devel
    - libtool-ltdl-devel
    - libunistring-devel.x86_64
    - libuuid
    - libuuid-devel
    - lynx
    - pcre
    - pcre-devel
    - postgresql96-devel
    - redis
    - xmlrpc-c-devel
  become: true
  become_method: sudo
  tags: ['kamailio']
  retries: 3
  delay: 3
  register: result
  until: result is success