# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Seteo esta variable que va en un Makefile
- set_fact: kernel="/usr/src/kernels/$(shell uname -r)"

# Descargo rtpengine desde la fuente, me descarga un .tar.gz
- name: Download of RTPengine-{{ rtpengine_version }}
  get_url: url={{ rtpengine_repo }} dest=/usr/src/
  retries: 3
  delay: 3
  register: result
  until: result is success

# Untareo el archivo recien descargado
- name: Untar the file
  unarchive: "src=/usr/src/{{ rtpengine_name }}.tar.gz dest=/usr/src/ remote_src=yes"

# Borro el tar
- name: Delete tar file
  file: "dest=/usr/src/{{ rtpengine_name }}.tar.gz state=absent"

###### Begin install #####
# https://voipmagazine.wordpress.com/2015/02/17/rtpengine-compilation-and-installation-in-fedora-redhat/

# Importacion de la llave para instalar ffmpeg (lo pide la version que usamos de rtpengine)
- name: Import of ffmpeg repository key (centos)
  rpm_key: state=present key=http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro validate_certs=no

# Instalo el repositorio
- name: Install of ffmpeg repository (centos)
  yum: name=http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm state=present
  retries: 3
  delay: 3
  register: result
  until: result is success

# Instalo los paquetes que se necesitan
- name: Install of ffmpeg (centos)
  yum: name={{ item }} state=present
  with_items:
      - ffmpeg
      - ffmpeg-devel
  become: true
  become_method: sudo
  retries: 3
  delay: 3
  register: result
  until: result is success

# Make de rtpengine en /usr/src/rtpengine/daemon
- name: Installation of RTPengine (centos)
  shell: "make chdir=/usr/src/{{ rtpengine_name }}/daemon"

# Aca hago la modificacion del makefile del modulo de kernel, uso la variable que setee en el set_fact
- name: Modify of the RTPengine kernel module to let it know where is our kernel (centos)
  lineinfile: "path=/usr/src/{{ rtpengine_name }}/kernel-module/Makefile regexp=\"^KSRC\" line=\"KSRC   ?= {{ kernel }}\""

# Se hace el make del modulo de kernel
- name: Installation of RTPengine kernel module (centos)
  shell: "make chdir=/usr/src/{{ rtpengine_name }}/kernel-module"

# Se inserta el modulo creado
- name: Insert the kernel module created for RTPengine (centos)
  shell: "insmod xt_RTPENGINE.ko chdir=/usr/src/{{ rtpengine_name }}/kernel-module"
  register: command_result
  failed_when: false

# Se hace make de una cosa llamada iptables-extension
- name: Installation of IPtables extensions (centos)
  shell: "make chdir=/usr/src/{{ rtpengine_name }}/iptables-extension"

# El so creado se mete a xtables no se bien para que pero supongo que para cargar las reglas de iptables para rtpengine
- name: Copy of iptables library to lib64/xtables (centos)
  copy: src=/usr/src/{{ rtpengine_name }}/iptables-extension/libxt_RTPENGINE.so dest=/lib64/xtables remote_src=yes

####### End of install #########