---

- name: Clonado de repositorio de RTPengine
  git:
          repo: "{{ rtpengine_repo }}"
          dest: /usr/src/rtpengine

- name: Build de rtpengine con dpkg
  shell: >
          chdir=/usr/src/rtpengine
          dpkg-buildpackage

- action: shell ls /usr/src/
  register: dirsrc

- name: Instalacion de los .deb de rtpengine
  apt:
          deb=/usr/src/{{ item }}
  with_items:
          - "{{ dirsrc.stdout_lines[7] }}"
          - "{{ dirsrc.stdout_lines[9] }}"
          - "{{ dirsrc.stdout_lines[8] }}"
          - "{{ dirsrc.stdout_lines[13] }}"
          - "{{ dirsrc.stdout_lines[10] }}"
          - "{{ dirsrc.stdout_lines[12] }}"
          - "{{ dirsrc.stdout_lines[3] }}"

