---

- include: sshkey_transfer.yml
  tags:
    - omniapp
    - postinstall

- include: django_migrations.yml
  tags:
    - omniapp
    - django-migrations
    - postinstall

- include: omniapp_second.yml
  tags:
    - omniapp
    - nginx


- include: wombat.yml
  tags:
    - omniapp
    - wombat
