---

- name: Upload nginx.conf configuration
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  become: true
  become_method: sudo

- name: Enable nginx
  shell: systemctl enable nginx
  become: true
  become_method: sudo

- name: Create of ominicontacto.conf
  template: src=templates/ominicontacto.conf.j2 dest=/etc/nginx/conf.d/ominicontacto.conf
  become: true
  become_method: sudo

- name: Copy of the certificates in nginx
  copy: "src={{ kamailio_location }}/etc/certs/{{ item }} dest={{ install_prefix }}nginx_certs/ remote_src=yes"
  with_items:
      - cert.pem
      - key.pem
  become: true
  ignore_errors: yes
  become_method: sudo
  tags: kamailio-cert
  notify: restart nginx

- name: Create of oml_uwgsi.ini script
  template: src=templates/oml_uwsgi.ini.j2 dest={{ install_prefix }}bin/oml_uwsgi.ini mode=755 owner={{ usuario }} group={{ usuario }}

- name: Create of omnileads service
  template: src=templates/omnileads.service dest=/etc/systemd/system/omnileads.service owner=root group=root mode=650
  become: true
  become_method: sudo

- name: Start the omnileads-daemon service
  command: "{{ item }}"
  with_items:
          - "systemctl daemon-reload"
          - "systemctl enable omnileads"
          - "service omnileads stop"
          - "service omnileads start"
  become: true
  become_method: sudo
  ignore_errors: yes

- name: Copy of the Kamailio cert in voip.cert
  template: src=templates/concatenate.sh dest={{ install_prefix }}bin/concatenate.sh mode=755
  ignore_errors: yes
  tags: kamailio-cert
  become: true
  become_method: sudo

- shell: "bash concatenate.sh chdir={{ install_prefix }}bin"
  tags: kamailio-cert
  ignore_errors: yes
  become: true
  become_method: sudo

- name: Generate changeip.sh script
  template: src=templates/changeip.sh.j2 dest={{ install_prefix }}bin/changeip.sh owner={{ usuario }} group={{ usuario }} mode=755

- name: Generate manage.sh script
  template: src=templates/manage.sh.j2 dest={{ install_prefix }}bin/manage.sh owner={{ usuario }} group={{ usuario }} mode=755

- name: Generate backup-restore.sh script
  template: src=templates/backup-restore.sh.j2 dest={{ install_prefix }}bin/backup-restore.sh owner={{ usuario }} group={{ usuario }} mode=755
