# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
# Playbook de instalacion de Omnileads
# Utilza como variables de entorno el archivo group_vars/all y el archivo de inventario hosts
# Utiliza como archivo de configuracion /var/tmp/ansible/ansible.cfg
# Cositas a tener en cuenta:
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_conditionals.html
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_loops.html
# https://docs.ansible.com/ansible/2.4/intro_configuration.html
---
# hosts: le decimos que seccion del hosts se va  usar: [omnileads]
- name: Instalacion de Omnileads
  hosts: omnileads-aio
# variables que vienen exportadas desde el deploy.sh
  vars:
          build_dir: "{{ BUILD_DIR }}"
# se piden las variables de superuser y el formato de conversion
# https://docs.ansible.com/ansible/2.6/user_guide/playbooks_prompts.html
# los pre_tasks son para validaciones de los inputs de los usuarios
  pre_tasks:

    ## Contraseña de postgresql

    # Checkeo si la base kamailio existe
      - name: Check if kamailio database exists
        shell: psql -U {{ postgres_user }} -h {{ database_fqdn }} -c '\l' |grep kamailio |awk -F '|' '{print $1}'
        environment:
          PGPASSWORD: "{{ postgres_password }}"
        register: kamailiodb_exists
        tags: ['never','postinstall']
        become: true
        become_method: sudo

      # tasks para cambiar el nombre de la db
      - name: Stop kamailio service
        service: name=kamailio state=stopped
        when: "'kamailio' in kamailiodb_exists.stdout and cluster == 0"
        tags: ['never','postinstall']

      - name: Stop omnileads service
        service: name=omnileads state=stopped
        when: "'kamailio' in kamailiodb_exists.stdout and cluster == 0"
        tags: ['never','postinstall']

      - name: Restart postgresql service
        service: name=postgresql-9.6 state=restarted
        when: "'kamailio' in kamailiodb_exists.stdout and cluster == 0"
        tags: ['never','postinstall']

      # Se cambia el nombre de la base de datos
      - name: Change the database name
        shell: psql -U postgres -h {{ database_ip }} -c 'ALTER DATABASE kamailio RENAME TO omnileads;'
        become: true
        environment:
          PGPASSWORD: "{{ postgres_password }}"
        become_user: postgres
        become_method: sudo
        when: "'kamailio' in kamailiodb_exists.stdout and cluster == 0"
        tags: ['never','postinstall']

# el gather_facts es para obtener valores de variables predeterminadas de ansible, la mas usada es ansible_os_family.
# Esta variable te dice que familia de OS es el servidor a deployar (Debian o RedHat)

  gather_facts: True

# Aca comienza la ejecucion de tasks. Las tasks se agrupan en roles, los roles se agrupan dependiendo del componente del sistema
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html
  roles:
          - prerequisitos
          - { role: database, tags: database }
          - {role: oml_server, tags: omniapp }
          - { role: asterisk, tags: asterisk }
          - {role: kamailio, tags: kamailio }
          - {role: omniapp_second, tags: omiapp }
          - { role: dialer, tags: dialer }
