# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
# Playbook de instalacion de Omnileads
# Utilza como variables de entorno el archivo group_vars/all y el archivo de inventario hosts
# Utiliza como archivo de configuracion /var/tmp/ansible/ansible.cfg
# Cositas a tener en cuenta:
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_conditionals.html
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_loops.html
# https://docs.ansible.com/ansible/2.4/intro_configuration.html
---

- name: Omnileads-Docker integration
  hosts: docker
  roles:
    - { role: docker }

# hosts: le decimos que seccion del hosts se va  usar: [omnileads]
- name: OMniLeads AIO installation
  hosts: prodenv-aio

# el gather_facts es para obtener valores de variables predeterminadas de ansible, la mas usada es ansible_os_family.
# Esta variable te dice que familia de OS es el servidor a deployar (Debian o RedHat)
  gather_facts: True

# Aca comienza la ejecucion de tasks. Las tasks se agrupan en roles, los roles se agrupan dependiendo del componente del sistema
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html
  roles:
          - prerequisitos
          - { role: database, tags: database }
          - {role: oml_server, tags: omniapp }
          - { role: asterisk, tags: asterisk }
          - {role: kamailio, tags: kamailio }
          - {role: omniapp_second, tags: omiapp }
          - { role: dialer, tags: dialer }

- name: OMniLeads Horizontal Cluster installation
  hosts: ['asterisk','kamailio','omniapp','database','dialer']
  gather_facts: True
  roles:
    - prerequisitos

- name: Get the omniapp omnileads ssh key (cluster)
  hosts: ['omniapp']
  pre_tasks:
    - name: Get the omniapp omnileads ssh key
      shell: cat {{ install_prefix }}.ssh/id_rsa.pub
      register: ssh_key
      tags: ['omniapp','asterisk','kamailio']
    - set_fact: sshkey={{ ssh_key.stdout }}
      tags: ['omniapp','asterisk','kamailio']

- name: Database sever installation
  hosts: ['database']
  gather_facts: True
  roles:
    - { role: database, tags: database }

- name: Asterisk server installation
  hosts: asterisk
  gather_facts: True
  pre_tasks:
    - set_fact: ssh_key="{{ hostvars[groups['omniapp'][0]].sshkey }}"
      tags: ['omniapp','asterisk']
    - name: Print omniapp omnileads user key in asterisk's root
      authorized_key: "user=root key={{ ssh_key }} state=present manage_dir=yes"
      tags: ['omniapp','asterisk']
  roles:
    - { role: asterisk, tags: asterisk }

- name: Kamailio server installation
  hosts: kamailio
  gather_facts: True
  pre_tasks:
    - set_fact: ssh_key="{{ hostvars[groups['omniapp'][0]].sshkey }}"
      tags: ['omniapp','kamailio']
    - name: Print omniapp omnileads user key in kamailio's root
      authorized_key: "user=root key={{ ssh_key }} state=present manage_dir=yes"
  roles:
    - { role: kamailio, tags: [kamailio'] }

- name: Omniapp server installation
  hosts: omniapp
  gather_facts: True
  roles:
    - { role: oml_server, tags: omniapp }
    - { role: omniapp_second, tags: omniapp }

- name: Dialer server installation
  hosts: dialer
  gather_facts: True
  roles:
    - { role: dialer, tags: dialer }
