---

- include: rtpengine.yml
  tags: kamailio

- include: kamailio.yml
  tags: kamailio

- include: postgresusers.yml
  tags: ['postgresusers','kamailio']

- include: kamailio-as-service.yml
  tags: kamailio

- include: certificate_CA.yml
  tags: kamailio-cert