---

- name: Clone of the RTPengine repo
  git: repo={{ rtpengine_repo }} dest=/usr/src/rtpengine
  register: command_result
  ignore_errors: yes

- name: Install of ffmpeg
  shell: rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
- shell: rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
  register: command_result
  failed_when:
    - "'transferencia fallida' in command_result.stderr"
    - "'failed' in command_result.stderr"

- name: Install of ffmpeg
  yum: name={{ item }} state=present
  with_items:
      - ffmpeg
      - ffmpeg-devel

- name: Installation of RTPengine
  shell: "make chdir=/usr/src/rtpengine/daemon"
- copy: src=/usr/src/rtpengine/daemon/rtpengine dest=/usr/local/bin remote_src=yes

- name: Modify of the RTPengine kernel module to let it know where is our kernel
  lineinfile: "path=/usr/src/rtpengine/kernel-module/Makefile regexp=\"^KSRC\" line=\"KSRC   ?= /usr/src/kernels/$(shell uname -r)\""

- name: Installation of RTPengine kernel module
  shell: "make chdir=/usr/src/rtpengine/kernel-module"
- shell: "insmod xt_RTPENGINE.ko chdir=/usr/src/rtpengine/kernel-module"
  register: command_result
  failed_when:
    - "'File exists' not in command_result.stderr"
    - "command_result.rc != 0"

- name: Installation of IPtables extensions
  shell: "make chdir=/usr/src/rtpengine/iptables-extension"
- copy: src=/usr/src/rtpengine/iptables-extension/libxt_RTPENGINE.so dest=/lib64/xtables remote_src=yes

- name: Copy of rptengine init script in sysconfig
  copy: src=/home/freetech/ominicontacto/ominicontacto_voip/kamailio-files/rtpengine_sysconfig dest=/etc/sysconfig/rtpengine remote_src=yes
- copy: src=/home/freetech/ominicontacto/ominicontacto_voip/kamailio-files/rtpengine.service dest=/etc/systemd/system remote_src=yes

- name: Modify of RTPengine sysconfig file
  template: src=templates/sysconfig_rtpengine.j2 dest=/etc/sysconfig/rtpengine

- name: Modify of /etc/rsyslog.conf
  template: src=templates/rsyslog.conf.j2 dest=/etc/rsyslog.conf

- name: Create rtpengine.log file
  file: path=/var/log/rtpengine/ state=directory mode=0755
- file: path=/var/log/rtpengine/rtpengine.log state=touch mode=0755

- name: Last changes
  shell: "{{ item }} chdir="
  with_items:
      - systemctl enable rtpengine.service
      - mkdir -p /var/spool/rtpengine
      - chmod +x /usr/local/bin/rtpengine
      - systemctl start rtpengine


