-

#----------------------------------------------------------------------
# Directorios básicos
#----------------------------------------------------------------------

- name: Create the required directories
  file: path={{item}} state=directory owner=freetech mode=0755
  sudo: yes
  # /home/freetech es incluido xq el permiso por default (0700) hace que

  with_items:
    - /home/freetech
    - /home/freetech/.pip
    - /home/freetech/ominicontacto/
  tags:
    - deploy


#----------------------------------------------------------------------
# pip / virtualenv
#----------------------------------------------------------------------

- name: Setup pip
  ini_file: >
    dest=/home/freetech/.pip/pip.conf
    section=install
    option='download-cache'
    value='/home/freetech/.pip/cache'
  tags:
    - virtualenv

- name: Upload built (rsync to /ominicontacto)
  # Copies xxx/app to /home/freetech/ominicontacto (/ominicontacto on dest is implicit)
  synchronize: >
    src={{BUILD_DIR}}
    dest=/home/freetech
    delete=yes checksum=yes times=no
  tags:
    - deploy

- name: Setup virtualenv
  pip: >
    requirements=/home/freetech/ominicontacto/requeriments.txt
    virtualenv=/home/ftsender/ominicontacto/virtualenv

  tags:
    - virtualenv

- name: Run Django migrations
  django_manage: >
      command=migrate
      app_path=/home/freetech/ominicontacto
      settings=fts_web.settings
      virtualenv=/home/freetech/ominicontacto/virtualenv
  tags:
    - deploy

