---

- hosts: omni-app
  tasks:
          - name: Create public key of freetech user
            user: name=freetech generate_ssh_key=yes ssh_key_bits=2048
            when: not post_install

          - name: Transfer ssh key from freetech's omniapp user to root's omnivoip user
            shell: cat /home/freetech/.ssh/id_rsa.pub
            register: ssh_key
            when: not post_install

          - authorized_key: user=root key={{ ssh_key.stdout }} state=present
            delegate_to: "{{ omnivoip_ip }}"
            when: not post_install


- hosts: omni-voip
  tasks:
          - name: Create public key of root user
            user: name=root generate_ssh_key=yes ssh_key_bits=2048
            when: not post_install

          - name: Transfer ssh key from root's omnivoip user to freetech's omniapp user
            shell: cat /root/.ssh/id_rsa.pub
            register: ssh_key
            when: not post_install

          - authorized_key: user=freetech key={{ ssh_key.stdout }} state=present
            delegate_to: "{{ omniapp_ip }}"
            when: not post_install

          - name: Editar el sudoers para ejecutar rsync sin pedir password de sudo
            lineinfile: "dest=/etc/sudoers line=\"freetech ALL = NOPASSWD: /usr/bin/rsync\""
            when: not post_install

- hosts: omni-app
  tasks:

          - name: Copy the Kamailio CA certificate to omni-app
            synchronize: src=/opt/kamailio-debian/etc/certs/demoCA/cert.pem dest=/home/freetech/ominicontacto/ominicontacto_app/static/ominicontacto/voip.cert times=yes
            become: yes
            become_user: freetech            
            delegate_to: "{{ omnivoip_ip }}"
            when: not post_install
