version: '3.7'
services:
  omnileads:
    cap_add:
      - SYS_ADMIN
    command:
      - /sbin/init
    container_name: ubuntu-base
    hostname: omnileads.example.com
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=America/Argentina/Cordoba
    image: freetechsolutions/base-ubuntu:latest
    logging:
      driver: syslog
    networks:
      default:
        ipv4_address: 172.16.0.2
    privileged: true
    ports:
     - "443:443/tcp"
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - type: bind
        source: "$PWD/../.."
        target: /opt/omnileads/ominicontacto/
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
volumes:
  ominicontacto:
