---

- name: Disable Selinux
  command: "{{ item }}"
  with_items:
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/sysconfig/selinux
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/selinux/config
  when: ansible_os_family == "RedHat"
  become: true
  become_method: sudo

- name: Exclude librabbitmq in list of repositories
  ini_file: "path=/etc/yum.repos.d/CentOS-Base.repo section={{ item }} option=exclude no_extra_spaces=yes value=librabbitmq* state=present"
  with_items:
      - base
      - updates
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Stop firewalld
  shell: "{{ item }}"
  with_items:
      - systemctl stop firewalld
      - systemctl disable firewalld

- name: Update/upgrade of centos
  yum: name='*' state=latest update_cache=yes
  become: true
  become_method: sudo
  when: LOCALHOST == "true"

- name: Install Development tools
  command: "yum -y groupinstall core base \"Development Tools\""
  become: true
  become_method: sudo

- name: Creation of sngrep repo
  template: src=templates/irontec.repo dest=/etc/yum.repos.d/irontec.repo
  become: true
  become_method: sudo

- name: Import of irontec public key
  shell: "rpm --import http://packages.irontec.com/public.key"
  become: true
  become_method: sudo

- name: Install of sngrep
  yum: name=sngrep state=present

- name: Download of epel-release repo
  command: "{{ item }}"
  with_items:
      - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  register: command_result
  failed_when:
    - "'transferencia fallida' in command_result.stderr"
    - "'failed' in command_result.stderr"
  become: true
  become_method: sudo
- meta: clear_host_errors

- name: Install of dependencies
  yum: name={{ item }} state=present
  with_items:
      - lynx
      - tftp-server
      - unixODBC
      - kernel-devel
      - git
      - sox
      - crontabs
      - cronie
      - openssl-devel
      - cronie-anacron
      - make
      - wget
      - gdb
      - git
      - which
      - vim
      - uuid-devel
      - net-tools
      - gnutls-devel
      - python-devel
      - texinfo
      - mariadb
      - mariadb-server
      - expect.x86_64
      - expect-devel.x86_64
      - MySQL-python.x86_64
      - kernel-devel
      - kernel-headers
      - acl
      - webkitgtk3-devel.x86_64
      - perl*
      #- librabbitmq*
      - pcre-devel
      - libpcap-devel
  become: true
  become_method: sudo

- name: Install of librabbitmq
  yum: "name={{ item }} state=present"
  with_items:
    - http://mirror.centos.org/centos/7/os/x86_64/Packages/librabbitmq-0.8.0-2.el7.x86_64.rpm
  become: true
  become_method: sudo

- name: Download of webtatic repo
  get_url: url=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm dest=/root/ validate_certs=no
  become: true
  become_method: sudo

- name: Installation of webtatic repo
  shell: "rpm -Uvh webtatic-release.rpm chdir=/root"
  register: command_result
  become: true
  become_method: sudo
  failed_when:
    - "'ya está instalado' not in command_result.stderr"
    - "'already installed' not in command_result.stderr"
    - "command_result.rc != 0"

- name: Install of php56
  yum: name={{ item }} state=present
  with_items:
      - php56w
      - php56w-pdo
      - php56w-mysql
      - php56w-mbstring
      - php56w-pear
      - php56w-process
      - php56w-xml
      - php56w-opcache
      - php56w-ldap
      - php56w-intl
      - php56w-soap
  become: true
  become_method: sudo
  when: asterisk_location != ""
- meta: clear_host_errors

- name: Download NodeJS setup script
  shell: "curl -sL https://rpm.nodesource.com/setup_8.x | bash -"
  become: true
  become_method: sudo

- name: Install NodeJS
  yum: name=nodejs state=present
  become: true
  become_method: sudo
