# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---
# se deshabilita selinux https://docs.ansible.com/ansible/2.5/modules/command_module.html
- name: Disable Selinux
  command: "{{ item }}"
  with_items:
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/sysconfig/selinux
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/selinux/config
  when: ansible_os_family == "RedHat"
  become: true
  become_method: sudo

# se agrega sslverify=0 en el yum.conf, esto es para que no joda por si hay repos con certificados expirados
# https://docs.ansible.com/ansible/2.5/modules/ini_file_module.html?highlight=ini_file

#- name: Do not verify ssl on repositories
#  ini_file: path=/etc/yum.conf section=main option=sslverify no_extra_spaces=yes value=0 state=present
#  become: true
#  become_method: sudo

- name: Configure yum for ansible
  ini_file: path=/etc/yum.conf section=main option="{{ item.option }}" no_extra_spaces=yes value="{{ item.value }}" state=present
  with_items:
    - { option: "sslverify", value: "0" }
    - { option: "timeout", value: "300" }
    - { option: "minrate", value: "100" }
  become: true
  become_method: sudo

  # Se excluye postgres de la lista de repositorios base y updates
- name: Exclude postgres in list of repositories
  ini_file: "path=/etc/yum.repos.d/CentOS-Base.repo section={{ item }} option=exclude no_extra_spaces=yes value=postgres* state=present"
  with_items:
    - base
    - updates
  become: true
  become_method: sudo

# Exluimos paquete librrabitmq para que no haga un upgrade este paquete
- name: Exclude librabbitmq in list of repositories
  ini_file: "path=/etc/yum.repos.d/CentOS-Base.repo section={{ item }} option=exclude no_extra_spaces=yes value=librabbitmq* state=present"
  with_items:
      - base
      - updates
  become: true
  become_method: sudo

# Se para y deshabilita firewalld
# https://docs.ansible.com/ansible/2.5/modules/shell_module.html#shell-module
- name: Stop firewalld
  shell: "{{ item }}"
  with_items:
      - systemctl stop firewalld
      - systemctl disable firewalld
  tags: ['kamailio','asterisk','omniapp']


# Update/upgrade del sistema, solo cuando LOCALHOST=true, osea si se ejecuta como deployed - deployer
# https://docs.ansible.com/ansible/2.5/modules/yum_module.html#yum-module
- name: Update/upgrade of centos
  yum: name='*' state=latest update_cache=yes skip_broken=yes
  become: true
  become_method: sudo
  when: LOCALHOST == "true"

# Se instala las Development Tools
- name: Install Development tools
  command: "yum -y groupinstall core base \"Development Tools\""
  become: true
  become_method: sudo

# Se crea el repo de sngrep desde el template https://docs.ansible.com/ansible/2.5/modules/template_module.html#template-module
#  https://docs.ansible.com/ansible-container/container_yml/template.html
- name: Creation of sngrep repo
  template: src=templates/irontec.repo dest=/etc/yum.repos.d/irontec.repo
  become: true
  become_method: sudo
  tags: ['asterisk']

# Se importa la rpm key
- name: Import of irontec public key
  rpm_key: state=present key=http://packages.irontec.com/public.key validate_certs=no
  become: true
  become_method: sudo
  tags: ['asterisk']

# Se instala sngrep
- name: Install of sngrep
  yum: name=sngrep state=present
  tags: ['asterisk']

# Se descarga e instala el repositorio epel-release
- name: Install of epel-release repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  become: true
  become_method: sudo
  tags: ['omniapp']

- meta: clear_host_errors

# Se instalan paquetes basicos que se necesitan
- name: Install of dependencies
  yum: name={{ item }} state=present
  with_items:
      - lynx
      - tftp-server
      - unixODBC
      - kernel-devel
      - git
      - sox
      - crontabs
      - cronie
      - openssl-devel
      - cronie-anacron
      - make
      - wget
      - gdb
      - git
      - which
      - vim
      - uuid-devel
      - net-tools
      - gnutls-devel
      - python-devel
      - texinfo
      - mariadb
      - mariadb-server
      - expect.x86_64
      - expect-devel.x86_64
      - MySQL-python.x86_64
      - kernel-devel
      - kernel-headers
      - acl
      - webkitgtk3-devel.x86_64
      - perl*
      #- librabbitmq*
      - pcre-devel
      - libpcap-devel
  become: true
  become_method: sudo
  tags: ['kamailio','asterisk','omniapp']

# Se instala por aparte librrabitmq para que no hinche las bolas ese paquete
- name: Install of librabbitmq
  yum: "name={{ item }} state=present"
  with_items:
    - http://mirror.centos.org/centos/7/os/x86_64/Packages/librabbitmq-0.8.0-2.el7.x86_64.rpm
  become: true
  become_method: sudo
  tags: ['asterisk']

# Se instala webtatic repo para instalar php56
- name: Install of webtatic repo
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present validate_certs=no
  become: true
  become_method: sudo
  tags: ['omniapp']

#Se instalan todos los paquetes de php56 -- FIX ME -- se necesitan todos los paquetes? verificar con desarrollo
- name: Install of php56
  yum: name={{ item }} state=present
  with_items:
      - php56w
      - php56w-pdo
      #- php56w-mysql
      - php56w-mbstring
      #- php56w-pear
      #- php56w-process
      #- php56w-xml
      - php56w-opcache
      #- php56w-ldap
      #- php56w-intl
      #- php56w-soap
      - php56w-fpm
      - php56w-pgsql
  become: true
  become_method: sudo
  when: asterisk_location != ""
  tags: ['omniapp']

- meta: clear_host_errors

#  Instalo paquetes de asterisk no se instalan con DOCKER=true
- name: Installation of asterisk packages
  yum: name={{ item }} state=present
  with_items:
      - ncurses-devel
      - ncurses-libs
      - libxml2
      - libxml2-devel
      - sqlite-devel
      - newt-devel
      - net-snmp-devel
      - unixODBC
      - unixODBC-devel
      - libtiff-devel
      - audiofile-devel
      - gtk2-devel
      - subversion
      - sendmail
      - sendmail-cf
      - lame
  become: true
  become_method: sudo
  when: ['DOCKER == "false"']
  tags: ['asterisk']

  # Instalo paquetes de kamailio
- name: Installation of kamailio packages
  yum: name={{ item }} state=present
  with_items:
    - libevent-devel
    - gcc
    - gcc-c++
    - bison
    - bison-devel
    - flex
    - expat
    - expat-devel
    - libuuid
    - libuuid-devel
    - xmlrpc-c-devel
    - lynx
    - pcre
    - pcre-devel
    - libtool-ltdl-devel
    - iptables-devel
    - iptables-services
    - libpcap-devel
    - glib2-devel
    - json-glib-devel
    - redis
    - hiredis
    - hiredis-devel
    - libunistring-devel.x86_64
  become: true
  become_method: sudo
  tags: ['kamailio']

- meta: clear_host_errors

  # Se instala el repo de postgresql9.6
- name: Install of postgresql 9.6
  yum: "name={{ postgresql_url }} state=present validate_certs=no "
  become: yes
  become_method: sudo

  #Se instalan todos los paquetes de postgresql96
- yum: name=postgresql96* state=present
  become: yes
  become_method: sudo

# Se instalan paquetes de App (centos)
- name: Install the app and services packages
  yum: "name={{ item }} state=present"
  with_items:
      - python-psycopg2.x86_64
      - python2-psycogreen.noarch
      - python
      - python-virtualenv
      - python-devel
      - mysql-connector-python
      - mysql-devel
      - nginx
      - nginx-all-modules
      - libjpeg-turbo-devel
      - libffi-devel
      - libffi
      - libpqxx
      - libpqxx-devel
      - cairo-devel
      - pycairo
      - pycairo-devel
      - cairo
      - libpqxx
      - libpqxx-devel
      - python-pycha
      - libxslt-devel
      - libxslt-python
      - libxslt
      - python-lxml
      - libxslt-python
      - postgresql-plpython
      - postgresql-libs
      - postgresql-devel
      - libsass-devel
      - libsass
      - python2-pip.noarch
  become: yes
  become_method: sudo
  tags: ['omniapp']

- meta: clear_host_errors

# El initdb de postgres toca ejecutarlo solo para centos
- name: Setup of postgresql
  command: "/usr/pgsql-9.6/bin/postgresql96-setup initdb"
  register: command_result
  failed_when:
    - "'is not empty' not in command_result.stdout"
    - "command_result.rc != 0"
  become: yes
  become_method: sudo

# Con service starteas stopeas restarteas y habilitas servicios. Aca lo hacemos con postgres en centos
- name: Start and enable postgres service
  service: name=postgresql-9.6.service state=restarted enabled=yes
  become: yes
  become_method: sudo
