# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# se crea el grupo de usuario omnileads
- name: Creation of {{ usuario }} group
  group: name={{ usuario }} state=present

- name: Creation of {{ usuario }} user
  user: name={{ usuario }} group={{ usuario }} create_home=yes shell=/bin/bash home=/opt/{{ usuario }} generate_ssh_key=yes ssh_key_bits=2048 state=present

# se crea el grupo de usuario omnileads
#- name: Creation of {{ usuario }} user and group
#  shell: addgroup -g 1000 -S {{ usuario }} &&  adduser -u 1000 -S {{ usuario }} -G {{ usuario }} -h {{ install_prefix }} -s /bin/bash
#  failed_when: false

- name: Create of .pgpass file
  template: src=roles/prerequisitos/templates/.pgpass dest={{ item }}.pgpass mode=0600 owner={{ usuario }} group={{ usuario }}
  with_items:
    - "{{ install_prefix }}"
    - /root/
  tags: postinstall

##################################
##         Centos tasks         ##
##################################

# se deshabilita selinux https://docs.ansible.com/ansible/2.5/modules/command_module.html
- name: Disable Selinux
  command: "{{ item }}"
  with_items:
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/sysconfig/selinux
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/selinux/config

- name: Set environment variables for this installation
  template: src=templates/omnileads_envars.sh dest=/etc/profile.d/ mode=644 owner=root group=root
  tags: postinstall
  when: is_docker == "false"

- name: Set MYSQL_PWD in omnileads_envars.sh
  blockinfile:
    path: /etc/profile.d/omnileads_envars.sh
    insertafter: EOF
    state: present
    block: |
      export MYSQL_PWD={{ mysql_root_password }}
  when: is_docker == "false"
  tags: ['never', 'postinstall']

- name: Write the /etc/hosts of server
  blockinfile:
    path: /etc/hosts
    insertafter: EOF
    state: present
    block: |
      {{ omni_ip }} {{ omni_fqdn }}
  tags: postinstall

# Se añaden los binarios que no van a necesitar password al hacerlos con sudo
- name: Edit sudoers to execute binaries withouth password
  lineinfile: dest=/etc/sudoers line={{ item }}
  with_items:
    - "{{ usuario }} ALL=(ALL:ALL)  ALL"
    - "{{ usuario }} ALL=(ALL) NOPASSWD: /usr/bin/rsync, /usr/sbin/asterisk"
  when: is_docker == "false"

# Se setea el timezone
- name: Set timezone of server
  timezone: name={{ TZ }}

##################################
###        Centos tasks         ##
##################################

- name: Configure yum for ansible
  ini_file: path=/etc/yum.conf section=main option="{{ item.option }}" no_extra_spaces=yes value="{{ item.value }}" state=present
  with_items:
    - { option: "sslverify", value: "0" }
    - { option: "timeout", value: "300" }
    - { option: "minrate", value: "100" }

# Se para y deshabilita firewalld
# https://docs.ansible.com/ansible/2.5/modules/shell_module.html#shell-module
- name: Stop firewalld
  shell: "{{ item }}"
  with_items:
      - systemctl stop firewalld
      - systemctl disable firewalld
  when: ansible_distribution != "Amazon"

# Se instalan paquetes basicos que se necesitan
- name: Install of dependencies
  yum: name={{ item }} state=present update_cache=yes
  with_items:
      - tftp-server
      - crontabs
      - gcc
      - gcc-c++
      - cronie
      - openssl-devel
      - cronie-anacron
      - make
      - gdb
      - which
      - vim
      - net-tools
      - gnutls-devel
      - python-devel
      - texinfo
      - kernel-headers
      - acl
      - bind-utils
  retries: 3
  delay: 3
  register: result
  until: result is success

# Se descarga e instala el repositorio epel-release
- name: Install of epel-release repo (centos)
  yum: name={{ epel_repository }} state=present update_cache=yes
  when: docker_distribution.stdout != '"Sangoma Linux"'

- name: Install of python-psycopg2
  yum: name=python-psycopg2 state=present
  when: postgresql_new_installed.rc != 3
  retries: 3
  delay: 3
  register: result
  until: result is success
