# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: Remove python2-devel package
  yum: name=python2-devel state=absent
  tags: ['never', 'postinstall']

# Se instalan paquetes de App
- name: Install omniapp packages
  yum: "name={{ item }} state=present"
  with_items:
    - cairo
    - cairo-devel
    - git
    - libxslt-devel
    - libxslt-python
    - libxslt
    - libjpeg-turbo-devel
    - libffi-devel
    - libffi
    - libpqxx
    - libpqxx-devel
    - libsass-devel
    - libsass
    - nginx
    - nginx-all-modules
    - pycairo
    - pycairo-devel
    - python3
    - python3-devel
    - python3-pip.noarch
    - python2-psycogreen.noarch
    - python-lxml
    - python-psycopg2.x86_64
    - python-virtualenv
    - redis
    - rsync
    - sox
  when: python_version.stdout != "Python 3.6.8"
  retries: 3
  delay: 3
  register: result
  until: result is success
  tags: postinstall

- name: Start and enable redis service
  service: name=redis state=restarted enabled=yes
  become: yes
  become_method: sudo
