---

- name: Instalacion de Getopt
  pear: name=Console_Getopt state=present

- name: Descarga de paquetes de asterisk
  get_url: "url={{ item }} dest=/usr/src/"
  register: destino
  with_items:
        - "{{ dahdi_linux }}"
        - "{{ libpri }}"
        - "{{ asterisk_v13 }}"
        - "{{ jansson }}"

- name: Descompresion de todos los paquetes
  unarchive: "src={{ item }} dest=/usr/src/ remote_src=yes"
  with_items:
          - "{{ destino.results[0].dest }}"
          - "{{ destino.results[1].dest }}"
          - "{{ destino.results[2].dest }}"
          - "{{ destino.results[3].dest }}"
  register: nombres_tar

- name: Borrado de los tar
  file: "dest={{ item }} state=absent"
  with_items:
         - "{{ nombres_tar.results[0].src }}"
         - "{{ nombres_tar.results[1].src }}"
         - "{{ nombres_tar.results[2].src }}"
         - "{{ nombres_tar.results[3].src }}"

- name: Instalacion de Dahdi Linux
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[1] }}"
  with_items:
        - "make all"
        - "make install"
        - "make config"

- name: Instalacion de libpri
  shell: "{{ item }} chdir=/usr/src/{{dirsrc.stdout_lines[4] }}"
  with_items:
          - "make"
          - "make install"

- name: Instalacion de jansson
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[2] }}"
  with_items:
          - "autoreconf -i"
          - "./configure"
          - "make"
          - "make install"

- name: Seteo del countrycode para asterisk
  debconf: name='libvpb0' question='libvpb0/countrycode' value={{ country_code }} vtype='string'
  when: ansible_os_family == "Debian"

- name: Instalacion de asterisk
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[0] }}"
  with_items:
          - "contrib/scripts/get_mp3_source.sh"
          - "contrib/scripts/install_prereq install"
          - "./configure"
          - "make"
          - "make install"
          - "make config"
          - "ldconfig"
          - "update-rc.d -f asterisk remove"

- name: Creacion de usuario asterisk y seteo de permisos
  shell: "{{ item }}"
  with_items:
          - "useradd -m asterisk"
          - "chown asterisk. /var/run/asterisk"
          - "chown -R asterisk. /etc/asterisk"
          - "chown -R asterisk. /var/lib/asterisk"
          - "chown -R asterisk. /var/log/asterisk"
          - "chown -R asterisk. /var/spool/asterisk"
          - "chown -R asterisk. /usr/lib/asterisk"
          - "rm -rf /var/www/html"

- name: Configurar upload_max_filesize en php.ini
  lineinfile: "dest=/etc/php5/apache2/php.ini regexp=\"^upload_max_filesize = \" insertafter=\"^upload_max_filesize = \" line=\"upload_max_filesize = 120M \""

- name: Backup de apache2.conf
  copy: "src=/etc/apache2/apache2.conf dest=/etc/apache2/apache2.conf_orig"

- name: Configurar el apache2.conf
  shell: "{{ item }}"
  with_items:
          - sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/apache2/apache2.conf
          - sed -i 's/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf
  notify: restart apache2
