---

- name: Update/upgrade of freepbx
  yum: name='*' state=latest update_cache=yes

- name: Install the necessary packages
  yum: name={{ item }} state=present
  with_items:
      - libevent*
      - json-*
      - libunistring-devel.x86_64
      - webkitgtk3-devel.x86_64
      - perl*
      - librabbitmq*
      - bison
      - pcre-devel
      - libpcap-devel
      - flex
      - git
      - gcc
      - gcc-c++
      - bison-devel
      - make
      - expat
      - expat-devel
      - net-snmp-devel
      - libxml2
      - libxml2-devel
      - openssl-devel
      - xmlrpc-c-devel
      - lynx
      - pcre
      - pcre-devel
      - ncurses-devel
      - ncurses-libs
      - gdb
      - unixODBC
      - unixODBC-devel
      - libtool-ltdl-devel
      - xmlrpc-c-devel
      - lynx
      - pcre
      - pcre-devel
      - iptables-devel
      - iptables-services
      - xmlrpc-c-devel
      - libpcap-devel
      - glib2-devel
      - json-glib-devel
      - libevent-devel
      - redis
      - hiredis
      - hiredis-devel
      - kernel-devel
      - kernel-headers
      - xmlrpc-c-devel
      - python-devel
      - libuuid
      - libuuid-devel

- name: Install postgres
  yum: name=postgres* state=present