---

- name: Clone of omni-voip repository
  git: repo={{ omnivoip_repo }} dest=/usr/src/oml-freepbx

- name: Install of postgresql 9.6
  yum: "name={{ postgresql_url }} state=present"
- yum: name=postgresql96* state=present

- name: Setup of postgresql
  shell: "{{ item }}"
  with_items:
      - /usr/pgsql-9.6/bin/postgresql96-setup initdb
      - systemctl enable postgresql-9.6.service
      - systemctl start postgresql-9.6.service
      - systemctl start redis
      - systemctl enable redis
  ignore_errors: yes
