---
- name: Instalacion de Omnileads en CentOS
  hosts: omni-centos
  # Siempre 'gather_facts' ya q' lo usaoms en varios 'when'
  # gather_facts: '{{ lookup("env","DO_CHECKS") }}'
  vars:
          build_dir: "{{ BUILD_DIR }}"

  roles:
          - oml_server
          - { role: omniapp_second, when: not post_install }
          - { role: deploy_supervision, when: not post_install }