---
- name: Instalacion de Omnileads en SangomaOS
  hosts: omni-freepbx
  # Siempre 'gather_facts' ya q' lo usaoms en varios 'when'
  # gather_facts: '{{ lookup("env","DO_CHECKS") }}'
  vars:
          build_dir: "{{ BUILD_DIR }}"

  roles:
          - {role: prerequisitos-sangoma, when: ansible_os_family == "Sangoma", tags: ['pre-sangoma']}
          - oml_server
          - omniapp_second
          - deploy_supervision


