---
- name: Instalacion de Omnileads en CentOS
  hosts: omni-centos
  # Siempre 'gather_facts' ya q' lo usaoms en varios 'when'
  # gather_facts: '{{ lookup("env","DO_CHECKS") }}'
  vars:
          build_dir: "{{ BUILD_DIR }}"

  roles:
          - {role: prerequisitos-sangoma, when: ansible_os_family == "RedHat", tags: ['pre-centos'] }
          - {role: oml_server, tags: ['omniapp_second']}
          - {role: kamailio-sangoma, when: ansible_os_family == "RedHat", tags: ['kamailio'] }
          - omniapp_second
          - {role: asterisk-freepbx, when: ansible_os_family == "RedHat", tags: ['asterisk-install'] }
          - {role: asterisk-freepbx-config, when: ansible_os_family == "RedHat", tags: ['asterisk-config'] }
          - {role: asternic, when: ansible_os_family == "RedHat", tags: ['asternic'] }
          - deploy_supervision


