---
- name: Instalacion de Omnileads en CentOS
  hosts: omni-centos
  # Siempre 'gather_facts' ya q' lo usaoms en varios 'when'
  # gather_facts: '{{ lookup("env","DO_CHECKS") }}'
  vars:
          build_dir: "{{ BUILD_DIR }}"
  gather_facts: True

  roles:
          - {role: prerequisitos-sangoma, when: ansible_os_family == "RedHat", tags: ['pre-centos'] }
          - {role: oml_server, tags: ['virtualenv']}
          - {role: kamailio-sangoma, when: ansible_os_family == "RedHat"}
          - {role: omniapp_second, tags: ['omniapp']}
          - {role: asterisk-freepbx, when: ansible_os_family == "RedHat", tags: ['omnivoip','asterisk-install'] }
          - {role: asterisk-freepbx-config, when: ansible_os_family == "RedHat", tags: ['omnivoip','asterisk-config'] }
          - {role: asternic, when: ansible_os_family == "RedHat", tags: ['omnivoip','asternic'] }
          - deploy_supervision


