---
- name: Instalacion de Omnileads en SangomaOS
  hosts: omni-freepbx
  # Siempre 'gather_facts' ya q' lo usaoms en varios 'when'
  # gather_facts: '{{ lookup("env","DO_CHECKS") }}'
  vars:
          build_dir: "{{ BUILD_DIR }}"

  roles:
          - {role: prerequisitos-sangoma, when: ansible_os_family == "Sangoma", tags: ['pre-sangoma']}
          - oml_server
          - {role: kamailio-sangoma, when: ansible_os_family == "Sangoma", tags: ['omnivoip','kamailio']}
          - omniapp_second
          - {role: asterisk-freepbx-sangoma, when: ansible_os_family == "Sangoma", tags: ['omnivoip','asterisk-config']}
          - {role: asternic, when: ansible_os_family == "Sangoma", tags: ['omnivoip','asternic']}
          - deploy_supervision



