---
- name: Instalacion de Omnileads en SangomaOS
  hosts: omni-freepbx
  # Siempre 'gather_facts' ya q' lo usaoms en varios 'when'
  # gather_facts: '{{ lookup("env","DO_CHECKS") }}'
  vars:
          build_dir: "{{ BUILD_DIR }}"
          rama: "{{ RAMA }}"
  remote_user: omnileads
  gather_facts: True

  roles:
          - {role: prerequisitos-sangoma, when: ansible_os_family == "Sangoma", tags: ['pre-sangoma']}
          - {role: oml_server, tags: ['virtualenv']}
          - {role: kamailio-sangoma, when: ansible_os_family == "Sangoma"}
          - {role: omniapp_second, tags: ['omniapp']}
          - {role: asterisk-freepbx-config, when: ansible_os_family == "Sangoma", tags: ['asterisk-config']}
          - {role: asternic, when: ansible_os_family == "Sangoma", tags: ['asternic']}
          - deploy_supervision



