---

- name: Creation of kamamailio run directories
  file: "path={{ item }} state=directory mode=0755"
  with_items:
      - /opt/kamailio/run/
      - /opt/kamailio/run/kamailio/

- name: Creation of kamailio user and group
  shell: "{{ item }}"
  with_items:
      #- mkdir -p /opt/kamailio/run/kamailio
      - groupadd -g 5000 kamailio
      - useradd -u 5000 -g 5000 -d /var/run/kamailio -M -s /bin/false kamailio
#  ignore_errors: yes

- name: Run kamailio as a service
  shell: "{{ item }}"
  with_items:
      - systemctl enable kamailio
      - systemctl daemon-reload
      - chown kamailio:kamailio -R /opt/kamailio
      - /opt/kamailio/sbin/kamdbctl restore /usr/src/oml-freepbx/kamailio-files/kamdb.sql

- name: Change network parameters in kamailio.cfg
  lineinfile: "dest=/opt/kamailio/etc/kamailio/kamailio.cfg regexp=\"MY_IP_ADDR!\" line=\"#!substdef \"!MY_IP_ADDR!{{ omnicentos_ip }}!g\"\""
  when: ansible_os_family == "RedHat"
- lineinfile: "dest=/opt/kamailio/etc/kamailio/kamailio.cfg regexp=\"MY_ASTERISK!\" line=\"#!substdef \"!MY_ASTERISK!{{ omnicentos_ip }}!g\"\""
  when: ansible_os_family == "RedHat"
- name: Change network parameters in kamailio.cfg
  lineinfile: "dest=/opt/kamailio/etc/kamailio/kamailio.cfg regexp=\"MY_IP_ADDR!\" line=\"#!substdef \"!MY_IP_ADDR!{{ omnifreepbx_ip }}!g\"\""
  when: ansible_os_family == "Sangoma"
- lineinfile: "dest=/opt/kamailio/etc/kamailio/kamailio.cfg regexp=\"MY_ASTERISK!\" line=\"#!substdef \"!MY_ASTERISK!{{ omnifreepbx_ip }}!g\"\""
  when: ansible_os_family == "Sangoma"
- lineinfile: "dest=/opt/kamailio/etc/kamailio/kamailio.cfg regexp=\"^alias=\" line=\"alias=\"{{ omnicentos_fqdn }}\"\""
  when: ansible_os_family == "RedHat" or ansible_os_family == "Sangoma"


