---

- name: Clonado de repositorio de Kamailio
  shell: >
          git clone --depth 1 --no-single-branch {{ item }} kamailio
          chdir=/usr/src/
  with_items:
          - "{{ kamailio_repo }}"
  register: command_result
  failed_when: "'already exists' not in command_result.stderr"

- name: Checkout del repositorio
  command: "{{ item }} chdir=/usr/src/kamailio/"
  with_items:
          - git checkout -b 4.4 origin/4.4
  register: command_result
  failed_when: "'already exists' not in command_result.stderr"

- name: Make Prefix kamailio.cfg
  shell: "make PREFIX=/opt/kamailio cfg chdir=/usr/src/kamailio"

- name: Se añade los modulos al modules.lst
  lineinfile:
          dest: /usr/src/kamailio/modules.lst
          regexp: '^include_modules='
          insertafter: '^include_modules= '
          line: 'include_modules= presence presence_xml app_python auth_ephemeral db_postgres ndb_redis presence tls uuid websocket'

- name: Copy of kamailio Makefile
  copy: src=/home/freetech/ominicontacto_voip/kamailio-files/Makefile dest=/usr/src/kamailio/modules/db_postgres/ remote_src=yes

- name: Make of kamailio
  shell: "{{ item }} chdir=/usr/src/kamailio"
  with_items:
      - make all
      - make install

