---

- name: Descarga de paquetes de FreePBX
  get_url: "url={{ item }} dest=/usr/src/"
  register: destino
  with_items:
          - "{{ freepbx }}"

- name: Descompresion de todos los paquetes
  unarchive: "src={{ item }} dest=/usr/src/ remote_src=yes"
  with_items:
          - "{{ destino.results[0].dest }}"
  register: nombres_tar

- name: Borrado de los tar
  file: "dest={{ item }} state=absent"
  with_items:
          - "{{ nombres_tar.results[0].src }}"

- action: shell ls /usr/src/
  register: dirsrc

- name: Instalacion de freepbx
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[2] }}"
  with_items:
          - ./start_asterisk start
          - ./install -n
  when: ansible_os_family == "Debian"

- name: Instalacion de freepbx
  shell: "./start_asterisk start chdir=/usr/src/{{ dirsrc.stdout_lines[3] }}"
  when: ansible_os_family == "RedHat"

- shell: "./install -n chdir=/usr/src/{{ dirsrc.stdout_lines[3] }}"
  register: command_result
  failed_when: "'freepbx.conf file detected' not in command_result.stderr"
  changed_when: False
  when: ansible_os_family == "RedHat"
- meta: clear_host_errors

- name: Copiado de archivos de base de datos y archivos de FreePBX
  shell: "{{ item }} chdir=/usr/src"
  with_items:
          - cp omnileads-AIO/asterisk/odbcinst.ini /etc/
          - cp omnileads-AIO/asterisk/odbc.ini /etc/
          - cp omnileads-AIO/asterisk/freepbx.service /etc/systemd/system/
  when: ansible_os_family == "Debian"
        
- name: Habilitar FreePBX y modulo RewriteEngine de Apache2
  shell: "{{ item }}"
  with_items:
          - systemctl enable freepbx
          - a2enmod rewrite
  when: ansible_os_family == "Debian"

- name: Modificar puerto por default de Apache
  shell: sed -i 's/:80/:8090/' /etc/apache2/sites-enabled/000-default.conf
  when: ansible_os_family == "Debian"
  notify: restart apache2

- name: Instalacion de pip
  apt: name=python-pip state=present
  when: ansible_os_family == "Debian"

- name: Instalacion de mysqldb module
  pip: name=MySQL-python
  when: ansible_os_family == "Debian"

- name: Add user of MySQL omnileads
  mysql_user: "name=omnileads host={{ item }} login_user=root password=admin123 priv=\"asterisk.*:ALL,GRANT\""
  with_items:
      - "localhost"
      - "{{ omniapp_ip }}"
  when: ansible_os_family == "Debian"

- name: Modificacion de my.cnf para que acepte conexiones remotas
  lineinfile: "dest=/etc/mysql/my.cnf regexp=\"^bind-address\" insertafter=\"^bind-address\" line=\"bind-address            = 0.0.0.0\""
  notify: restart mysql
  when: ansible_os_family == "Debian"






