---

# Bueno este paso es importante. El comando kamdbctl es para interactuar con la base de datos. http://manpages.ubuntu.com/manpages/trusty/man8/kamdbctl.8.html
# Aca lo que se esta haciendo es creando la base de datos y las tablas que necesitan los modulos de kamailio. Se usa la  configuracion que hay en el kamctlrc

# El initdb de postgres toca ejecutarlo solo para centos
- name: Setup of postgresql
  command: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb"
  register: commandresult
  failed_when:
    - "'is not empty' not in commandresult.stdout"
    - "commandresult.rc != 0"
  tags: postinstall
  when: ansible_os_family == "RedHat" and postgresql_new_installed.rc != 3

# Se modifica el pg_hba.conf
- name: Modify of pg_hba.conf file
  template: src=templates/pg_hba.conf.j2 dest={{ pg_lib_location }}/pg_hba.conf
  become: true
  become_method: sudo
  when: postgresql_new_installed.rc != 3
  tags: postinstall

#Se modifica la ip en la que escucha postgres
- name: Modify postgresql listen address (centos)
  lineinfile: path={{ pg_lib_location }}/postgresql.conf regexp="^#listen_addresses" line="listen_addresses = '*'" state=present
  tags: postinstall
  when: postgresql_new_installed.rc != 3

# Restarteamos servicio
- name: Restart postgres service
  service: name=postgresql{{prefix}}{{ postgresql_version }}{{sufix}} state=restarted enabled=yes
  when: postgresql_new_installed.rc != 2
  tags: postinstall

# Se crea el usuario de postgres
- name: Create/modify postgres user
  postgresql_user: name={{ postgres_user }} password={{ postgres_password }} role_attr_flags=SUPERUSER encrypted=yes
  become: yes
  become_method: sudo
  become_user: postgres
  tags: postinstall

# Se crea el usuario de postgres
- name: Create ro postgres user
  postgresql_user: name={{ postgres_user}}ro password={{ postgres_password }}ro role_attr_flags=SUPERUSER encrypted=yes
  become: yes
  become_method: sudo
  become_user: postgres

# Se crea base de datos omnileads
- name: Create of the database
  postgresql_db: name={{ postgres_database }} state=present login_user={{ postgres_user }} login_password={{ postgres_password }} owner={{ postgres_user }} login_host={{ database_fqdn }}

# Se crea el lenguaje plpythonu a las bases de datos mencionadas.
- name: Createlang of the database
  shell: psql -d {{ item }} -c 'CREATE EXTENSION plpythonu'
  with_items:
    - "{{ postgres_database }}"
    - template1
  become: true
  become_user: postgres
  failed_when: false
