# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

##################
## Centos tasks ##
##################

# Se descarga e instala el repositorio epel-release
- name: Install of epel-release repo (centos)
  yum: name={{ epel_repository }} state=present update_cache=yes
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat" and postgresql_new_installed.rc != 3

- name: Download postgresql-{{ postgresql_version }} key
  rpm_key: key="{{ postgresql_key }}" state=present validate_certs=no
  when: ansible_os_family == "RedHat" and postgresql_new_installed.rc != 3
  retries: 3
  delay: 3
  register: result
  until: result is success

# Se instala el repo de postgresql
- name: Install of postgresql-{{ postgresql_version }} repository
  yum: name={{ postgresql_repo }} state=present validate_certs=no update_cache=yes
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat" and postgresql_new_installed.rc != 3
  retries: 3
  delay: 3
  register: result
  until: result is success

  #Se instalan todos los paquetes de postgresql
- name: Install of postgresql-{{ postgresql_version }} (centos)
  shell: "yum install postgresql{{ postgresql_version }}* --skip-broken -y"
  #yum: name='postgresql{{ postgresql_version }}*' state=present
  when: ansible_os_family == "RedHat" and postgresql_new_installed.rc != 3
  retries: 3
  delay: 3
  register: result
  until: result is success

- name: Install of python-psycopg2 (centos)
  yum: name="{{ psycopg2_repo }}" state=present
  when: ansible_os_family == "RedHat" and postgresql_new_installed.rc != 3
  retries: 3
  delay: 3
  register: result
  until: result is success

############################
## Ubuntu / Debian tasks ##
###########################

- name: Get debian/ubuntu release
  shell: lsb_release -cs
  register: release
  tags: postinstall
  when: ansible_os_family == "Debian" and postgresql_new_installed.rc != 3

- name: Add the postgresql repository key (debian/ubuntu)
  apt_key: url={{ postgresql_key }} validate_certs=no state=present
  retries: 3
  delay: 3
  register: result
  until: result is success
  tags: postinstall
  when: ansible_os_family == "Debian" and postgresql_new_installed.rc != 3

- name: Download postgresql-{{ postgresql_version }} repository (debian/ubuntu)
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ release.stdout }}-pgdg main" filename=pgdg state=present update_cache=yes
  retries: 3
  delay: 3
  register: result
  until: result is success
  tags: postinstall
  when: ansible_os_family == "Debian" and postgresql_new_installed.rc != 3

#Se intala postgresql debian
- name: Install of postgresql {{ postgresql_version }} (debian/ubuntu)
  apt: name={{ item }} state=present
  with_items:
    - postgresql-plperl-{{ postgresql_version }}
    - postgresql-{{ postgresql_version }}
    - python-psycopg2
  retries: 3
  delay: 3
  register: result
  until: result is success
  tags: postinstall
  when: ansible_os_family == "Debian" and postgresql_new_installed.rc != 3
