---

- include: installations.yml
  tags: postinstall

- include: configurations.yml

# Se incuyen tareas para hacer upgrade de db postregs para postinstall y se detecta que postgres 9.6 esta instalado
- include: db_upgrade.yml
  tags: ['never','postinstall']
  when: postgresql_new_installed.rc == 2
