---

- name: Include centos variables
  include_vars: group_vars/centos_vars.yml
  tags: postinstall

- include: installations.yml
  tags: postinstall

- include: configurations.yml

- include: db_upgrade.yml
  tags: ['never','postinstall']
  when: postgresql_new_installed.rc == 2

