---

- include: installations.yml

- include: configurations.yml

- include: roles/prerequisitos/tasks/reboot.yml
  when: cluster != 0 and ansible_os_family == "RedHat"

- name: Wait for the server to finish rebooting
  become: no
  local_action: wait_for host="{{ database_ip }}" delay=15 state=started port={{ ansible_ssh_port }} timeout=600
  tags: reboot
  when: ansible_os_family == "RedHat" and cluster !=0
