---

- name: Instalacion de Omnileads en Centos
  hosts: omni-centos
  roles:
          # Instalación de paquetes y dependencias de omnivoip y setup inicial del server
          # Instalación de asterisk y freepbx
          - {role: asterisk-freepbx, when: ansible_os_family == "RedHat", tags: ['omnivoip','asterisk-install'] }
          # Instalación y configuración de Kamailio
          - {role: kamailio-sangoma, when: ansible_os_family == "RedHat", tags: ['omnivoip','kamailio'] }
          # Configuración de asterisk/freepbx para funcionar con Omnileads
          - {role: asterisk-freepbx-config, when: ansible_os_family == "RedHat", tags: ['omnivoip','asterisk-config'] }
          # Seteo de asternic
          - {role: asternic, when: ansible_os_family == "RedHat", tags: ['omnivoip','asternic'] }

