---

- name: Modificacion sshd_config
  shell: >
          sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
  notify: restart ssh 

- name: FQDN en /etc/hostname
  template: src=templates/hostname-omnivoip.j2 dest=/etc/hostname 

- name: Cambiar FQDN en /etc/hosts
  template: src=templates/hosts.j2 dest=/etc/hosts

- name: Update/upgrade del sistema
  apt:
          update_cache: yes
          cache_valid_time: 12
          upgrade: yes
          dpkg_options: 'force-confdef'

- name: install linux linux-headers
  action: shell apt-get install -y linux-headers-$(uname -r)
  ignore_errors: True
  tags:
          - build

- name: Instalación de mysqlserver
  apt:  
        name: mysql-server 
        state: present 
        dpkg_options: 'force-confdef' 


- name: Instalación de dependencias / librerias de omni-voip
  apt:  
        name={{ item }} state=present 
  with_items:
                  - build-essential
                  - debhelper
                  - iptables-dev
                  - libcurl4-openssl-dev
                  - libpcre3-dev
                  - libxmlrpc-core-c3-dev
                  - markdown
                  - libglib2.0-dev
                  - libhiredis-dev
                  - dkms
                  - git
                  - libevent-dev
                  - libbencode-perl
                  - libcrypt-rijndael-perl
                  - libdigest-hmac-perl
                  - libio-socket-inet6-perl
                  - libsocket6-perl
                  - libb-hooks-op-check-perl
                  - libexporter-tidy-perl
                  - libpcap0.8-dev
                  - libpcap-dev
                  - libssl-dev
                  - libio-socket-ip-perl
                  - libavcodec-dev
                  - libavfilter-dev
                  - libavformat-dev
                  - libavresample-dev
                  - libavutil-dev
                  - gcc
                  - flex
                  - bison
                  - libmysqlclient-dev
                  - make
                  - libssl-dev
                  - libcurl4-openssl-dev
                  - libxml2-dev
                  - libpcre3-dev
                  - libpq-dev
                  - libpq5
                  - redis-server
                  - python-dev
                  - uuid
                  - uuid-dev
                  - libunistring-dev
                  - libjson-glib-dev
                  - postgresql-client
                  - vim
                  - php5-pgsql
                  - openssh-server
                  - apache2
                  - mysql-client
                  - bison
                  - flex
                  - php5
                  - php5-curl
                  - php5-cli
                  - php5-mysql
                  - php-pear
                  - php5-gd
                  - curl
                  - sox
                  - libncurses5-dev
                  - libssl-dev
                  - libmysqlclient-dev
                  - mpg123
                  - libxml2-dev
                  - libnewt-dev
                  - sqlite3
                  - libsqlite3-dev
                  - pkg-config 
                  - automake
                  - libtool
                  - autoconf
                  - git
                  - curl
                  - ntp
                  - unixodbc-dev
                  - uuid
                  - uuid-dev
                  - libasound2-dev
                  - libogg-dev
                  - libvorbis-dev
                  - libcurl4-openssl-dev
                  - libical-dev
                  - libneon27-dev
                  - libsrtp0-dev
                  - libspandsp-dev
                  - sudo
                  - libmyodbc
                  - subversion
                  - odbc-postgresql



