---

- set_fact: mysql_host=127.0.0.1
  tags: postinstall

- include: installations.yml
  
- include: mariadb.yml

- include: roles/prerequisitos/tasks/reboot.yml
  when: ansible_connection != "local"

- name: Wait for the server to finish rebooting
  become: no
  wait_for: host="{{ omni_ip }}" delay=15 state=started port={{ ansible_ssh_port }} timeout=600
  delegate_to: localhost
  when: iface == "none"
