---

# Docker hosts general variable

# Images used
asterisk_image: andrius/asterisk:debian-buster-slim-16-current
base_image: alpine:3.9
dialer_image: tomcat:8.5-alpine
kamailio_image: kamailio/kamailio-ci:5.2
mariadb_image: bitnami/mariadb:latest
nginx_image: nginx:mainline-alpine
postgres_image: postgres:{{ postgresql_version }}
rtpengine_image: bitnami/minideb
redis_image: redis:5-alpine
# Images for EFK
elasticsearch_image: elasticsearch:7.1.0
fluentd_image: qqbuby/fluentd:v1.2-es
kibana_image: kibana:7.1.0

# Settings of folder structure
usuario: "{{ docker_user }}"
deploy_location: "/etc/docker/omnileads/{{ customer }}"
asterisk_location:
ast_local_location: "{{ deploy_location }}/asterisk"
ast_agis_location: "{{ ast_local_location }}/agis"
ast_conf_location: "{{ ast_local_location }}/conf"
ast_other_location: "{{ ast_local_location }}/others"
certs_location: "{{ deploy_location }}/certs"
conversor_location: "{{ ast_other_location }}"
efk_location: "{{ deploy_location }}/efk"
nginx_location: "{{ deploy_location }}/nginx"
omniapp_location: "{{ deploy_location }}/omniapp"
odbc_location: "{{ ast_local_location }}"

# Docker hub credentials to push images
docker_login_user:
docker_login_email:
docker_login_pass:
