---

- name: Disable Selinux
  shell: "{{ item }}"
  with_items:
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/sysconfig/selinux
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/selinux/config

- name: Update/upgrade of centos
  yum: name='*' state=latest update_cache=yes

- name: Install Development tools
  shell: "yum -y groupinstall core base \"Development Tools\""

- name: Install of dependencies
  yum: name={{ item }} state=present
  with_items:
       - lynx
       - tftp-server
       - unixODBC
       - mariadb-server
       - mariadb
       - httpd
       - ncurses-devel
       - sendmail
       - sendmail-cf
       - sox
       - newt-devel
       - libxml2-devel
       - libtiff-devel
       - audiofile-devel
       - gtk2-devel
       - subversion
       - kernel-devel
       - git
       - crontabs
       - cronie
       - cronie-anacron
       - wget
       - vim
       - uuid-devel
       - sqlite-devel
       - net-tools
       - gnutls-devel
       - python-devel
       - texinfo
       - MySQL-python.x86_64
- name: Install php 5.6
  shell: "{{ item }}"
  with_items:
      - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
  ignore_errors: yes

- yum: name={{ item }} state=present
  with_items:
      - php56w
      - php56w-pdo
      - php56w-mysql
      - php56w-mbstring
      - php56w-pear
      - php56w-process
      - php56w-xml
      - php56w-opcache
      - php56w-ldap
      - php56w-intl
      - php56w-soap
      - php56w-pgsql

- name: Install of NodeJS
  shell: "curl -sL https://rpm.nodesource.com/setup_8.x | bash -"
  ignore_errors: yes
- yum: name=nodejs state=present

- name: Install Console_Getopt
  pear: name=Console_Getopt state=present


