---

- name: Clone of omni-voip repository
  git: repo={{ omnivoip_repo }} dest=/usr/src/oml-freepbx

- name: Install of postgresql 9.6
  yum: "name={{ postgresql_url }} state=present validate_certs=no "
- yum: name=postgresql96* state=present

- name: Install of the other packages
  yum: "name={{ item }} state=present"
  with_items:
      - python-psycopg2.x86_64
      - python
      - python-virtualenv
      - python-devel
      - mysql-connector-python
      - mysql-devel
      - nginx
      - nginx-all-modules
      - libjpeg-turbo-devel
      - libffi-devel
      - libffi
      - cairo-devel
      - pycairo
      - pycairo-devel
      - cairo
      - python-pycha
      - libxslt-devel
      - libxslt-python
      - libxslt
      - python-lxml
      - libxslt-python
      - postgresql-plpython
      - postgresql-devel
      - libsass-devel
      - libsass
      - libpqxx
      - libpqxx-devel

- name: Setup of postgresql
  shell: "{{ item }}"
  with_items:
      - /usr/pgsql-9.6/bin/postgresql96-setup initdb
      - systemctl enable postgresql-9.6.service
      - systemctl start postgresql-9.6.service
      - systemctl start redis
      - systemctl enable redis
  ignore_errors: yes
