---

- name: Clone of omni-voip repository
  git: repo={{ omnivoip_repo }} dest=/usr/src/oml-freepbx

- name: Install of postgresql 9.6
  yum: "name={{ postgresql_url }} state=present validate_certs=no "
- yum: name=postgresql96* state=present

- name: Install of the other packages
  yum: "name={{ item }} state=present"
  with_items:
      - python-psycopg2.x86_64
      - python2-psycogreen.noarch
      - python
      - python-virtualenv
      - python-devel
      - mysql-connector-python
      - mysql-devel
      - nginx
      - nginx-all-modules
      - libjpeg-turbo-devel
      - libffi-devel
      - libffi
      - libpqxx
      - libpqxx-devel
      - cairo-devel
      - pycairo
      - pycairo-devel
      - cairo
      - libpqxx
      - libpqxx-devel
      - python-pycha
      - libxslt-devel
      - libxslt-python
      - libxslt
      - python-lxml
      - libxslt-python
      - postgresql-plpython
      - postgresql-libs
      - postgresql-devel
      - libsass-devel
      - libsass
      - python2-pip.noarch

- name: Install php 5.6
  shell: "{{ item }}"
  with_items:
      - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
  ignore_errors: yes

- yum: name={{ item }} state=present
  with_items:
      - php56w
      - php56w-pdo
      - php56w-mysql
      - php56w-mbstring
      - php56w-pear
      - php56w-process
      - php56w-xml
      - php56w-opcache
      - php56w-ldap
      - php56w-intl
      - php56w-soap
      - php56w-pgsql

- name: Setup of postgresql
  shell: "{{ item }}"
  with_items:
      - /usr/pgsql-9.6/bin/postgresql96-setup initdb
      - systemctl enable postgresql-9.6.service
      - systemctl start postgresql-9.6.service
      - systemctl start redis
      - systemctl enable redis
  ignore_errors: yes
