---

- name: Descarga de paquetes de FreePBX
  get_url: "url={{ item }} dest=/usr/src/"
  register: destino
  with_items:
          - "{{ freepbx }}"

- name: Descompresion de todos los paquetes
  unarchive: "src={{ item }} dest=/usr/src/ remote_src=yes"
  with_items:
          - "{{ destino.results[0].dest }}"
  register: nombres_tar

- name: Borrado de los tar
  file: "dest={{ item }} state=absent"
  with_items:
          - "{{ nombres_tar.results[0].src }}"

- action: shell ls /usr/src/
  register: dirsrc

- name: Instalacion de freepbx
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[2] }}"
  with_items:
          - ./start_asterisk start
          - ./install -n

- name: Copiado de archivos de base de datos y archivos de FreePBX
  shell: "{{ item }} chdir=/usr/src"
  with_items:
          - cp omnileads-AIO/asterisk/odbcinst.ini /etc/
          - cp omnileads-AIO/asterisk/odbc.ini /etc/
          - cp omnileads-AIO/asterisk/freepbx.service /etc/systemd/system/
        
- name: Habilitar FreePBX y modulo RewriteEngine de Apache2
  shell: "{{ item }}"
  with_items:
          - systemctl enable freepbx
          - a2enmod rewrite

- name: Modificar puerto por default de Apache
  shell: sed -i 's/:80/:8090/' /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2

- name: Instalacion de pip
  apt: name=python-pip state=present

- name: Instalacion de mysqldb module
  pip: name=MySQL-python

- name: Agregar usuario de mysql omnileads
  mysql_user: "name=omnileads host={{ omniapp_ip }} login_user=root password=admin123 priv=\"asterisk.*:ALL,GRANT\""

- name: Modificacion de my.cnf para que acepte conexiones remotas
  lineinfile: "dest=/etc/mysql/my.cnf regexp=\"^bind-address\" insertafter=\"^bind-address\" line=\"bind-address            = 0.0.0.0\""
  notify: restart mysql

- include: apache.yml





