---

- name: Delete of asterisk files managed by omnileads
  shell: "rm -rf {{ item }} chdir=/opt/asterisk-13/etc/asterisk/"
  with_items:
      - extensions_custom.conf
      - extensions_fts.conf
      - sip_custom.conf
      - extconfig.conf
      - amd.conf
      - func_odbc.conf
      - http_custom.conf
      - func_odbc.conf
      - cdr_adaptive_odbc.conf
      - manager_custom.conf
      - queues_custom.conf
      - globals_custom.conf
      - pjsip.transports_custom.conf
      - res_odbc_custom.conf
  tags:
    - issabel
    - postinstall

- shell: "rm -rf {{ item}} chdir=/opt/asterisk-13/var/lib/asterisk/agi-bin/"
  with_items:
      - omni-asterisk-logout.php
      - omni-blacklist.php
      - omni-grabaciones.php
      - omni-dialednum.php
      - generate_outbound_route_context.php
  tags:
    - issabel
    - postinstall

- name: Config of asterisk-freepbx for OML
  file: "state=link src=/opt/omnileads/ominicontacto/ominicontacto_voip/asterisk-files/{{ item }} dest=/opt/asterisk-13/etc/asterisk/{{ item }} force=true"
  with_items:
      - extensions_custom.conf
      - extensions_fts.conf
      - sip_custom.conf
      - extconfig.conf
      - amd.conf
      - func_odbc.conf
      - cdr_adaptive_odbc.conf
      - http_custom.conf
      - manager_custom.conf
      - queues_custom.conf
      - globals_custom.conf
      - http_custom.conf
      - pjsip.transports_custom.conf
      - res_odbc_custom.conf
  tags:
    - issabel
    - postinstall

- copy: "src=/opt/omnileads/ominicontacto/ominicontacto_voip/asterisk-files/{{ item }} dest=/opt/asterisk-13/var/lib/asterisk/agi-bin/{{ item }} mode=755 remote_src=yes owner=omnileads group=omnileads"
  with_items:
      - omni-asterisk-logout.php
      - omni-blacklist.php
      - omni-dialednum.php
      - omni-grabaciones.php
      - generate_outbound_route_context.php
  tags:
    - issabel
    - postinstall

- name: Create of asterisk cron
  file: path=/var/spool/cron/asterisk state=touch owner=root group=root mode=755

- name: Asterisk crontab modification
  lineinfile: "dest=/var/spool/cron/asterisk line=\"*/5 * * * * /opt/asterisk-13/asterisk/agi-bin/omni-asterisk-logout.php\""
  tags: issabel

- name: Create /usr/local/parselog
  file: dest=/usr/local/parselog state=directory mode=0755
  tags: issabel

- name: Set ownership to asterisk user
  shell: "{{ item }} chdir=/opt/omnileads/ominicontacto/ominicontacto_voip/asterisk-files"
  with_items:
      - cp update_mix_mixmonitor.pl /usr/local/parselog
      - chmod +x /usr/local/parselog/update_mix_mixmonitor.pl
      - chown omnileads.omnileads -R /usr/local/parselog
      - cp /opt/omnileads/ominicontacto/ominicontacto_voip/extra-files/odbcinst.ini /etc/
      - cp /opt/omnileads/ominicontacto/ominicontacto_voip/extra-files/odbc.ini /etc/
      - mkdir /opt/asterisk-13/var/lib/asterisk/sounds/es
      - mkdir /opt/asterisk-13/var/lib/asterisk/sounds/en
      - tar xzvf es-oml.tgz -C /opt/asterisk-13/var/lib/asterisk/sounds/es/
      - tar xzvf en-oml.tgz -C /opt/asterisk-13/var/lib/asterisk/sounds/en/
  ignore_errors: yes
  tags: issabel

- name: Add web enabled in /etc/asterisk/manager.conf
  ini_file: "path=/opt/asterisk-13/etc/asterisk/manager.conf section=general option=webenabled no_extra_spaces=yes value=yes state=present"
  tags: issabel

- name: Add web nocolor=yes in /etc/asterisk/asterisk.conf
  ini_file: "path=/opt/asterisk-13/etc/asterisk/asterisk.conf section=options option=nocolor no_extra_spaces=yes value=yes state=present"
  tags: issabel

- name: Install Mysql-python DB module
  pip: name=MySQL-python
  when: ansible_os_family == "Sangoma"
  tags: issabel

- name: Add user of MySQL omnileads
  mysql_user: "name=omnileads host={{ item }} login_user=root login_password={{ mysql_root_password }} password=admin123 priv=\"asterisk.*:ALL,GRANT\""
  with_items:
      - "localhost"
      - "127.0.0.1"
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  tags: issabel

- name: Stop freepbx firewall
  shell: "{{ item }}"
  with_items:
      - systemctl stop firewalld
      - systemctl disable firewalld
  tags: issabel

- name: Start asterisk
  shell: "service asterisk start"
  become: yes
  become_method: sudo