---

- name: Createlang of the database
  shell: "createlang plpythonu kamailio"
  become: yes
  become_user: postgres
  when: not post_install

- name: Run Django migrations
  django_manage: >
          command={{ item }}
          app_path={{ django_dir }}
          settings=ominicontacto.settings
          virtualenv={{ django_dir }}/virtualenv
  with_items:
          - migrate
          - "createsuperuser --noinput --username={{ admin_user }} --email=admin@example.com"
  ignore_errors: yes
  notify: restart ominicontacto-daemon
  tags:
          - deploy

- name: Change password of superuser
  template: "src=templates/changepassword.sh.j2 dest={{ django_dir }}/changepassword.sh mode=0755"

- name: Change password
  shell: "./changepassword.sh chdir={{ django_dir }}"
  environment:
          DJANGO_SETTINGS_MODULE: "ominicontacto.settings"
