---

- set_fact: static_route=/opt/omnileads/ominicontacto/ominicontacto_app/static/ominicontacto

- name: Change the ip address in config.js
  template: "src=templates/config.js.j2 dest={{ static_route }}/JS/config.js owner=omnileads group=omnileads"

- name: Createlang of the database
  shell: "createlang plpythonu kamailio"
  become: yes
  become_user: postgres
  register: command_result
  failed_when:
    - "'ya está instalado' not in command_result.stderr"
    - "'already installed' not in command_result.stderr"
    - "command_result.rc != 0"

- name: Run Django migrations
  django_manage: >
          command={{ item }}
          app_path={{ django_dir }}
          settings=ominicontacto.settings
          virtualenv=/opt/omnileads/virtualenv
  with_items:
          - migrate
          - "createsuperuser --noinput --username={{ admin_user }} --email=admin@example.com"
          - collectstatic
          - compress
          - regenerar_asterisk
  environment:
    PYTHONPATH: '/opt/omnileads/ominicontacto:/opt/omnileads/local'
  become: yes
  become_method: su
  become_user: omnileads
  ignore_errors: yes

- name: Change password of superuser
  template: "src=templates/changepassword.sh.j2 dest={{ django_dir }}/changepassword.sh mode=0755"

- name: Change password
  shell: "./changepassword.sh chdir={{ django_dir }}"
  environment:
          DJANGO_SETTINGS_MODULE: "ominicontacto.settings"
          PYTHONPATH: '/opt/omnileads/ominicontacto:/opt/omnileads/local'

- name: Erase the script for changing superuser password
  file: path=/opt/omnileads/ominicontacto/changepassword.sh state=absent

#- name: Change permissions on id_rsa
#  shell: "chmod 700 /opt/omnileads/.ssh/id_rsa"
#  when: ansible_os_family == "RedHat" or ansible_os_family == "Sangoma"


