---

- name: Createlang of the database
  shell: "createlang plpythonu kamailio"
  become: yes
  become_user: postgres
  when: not post_install
  ignore_errors: yes

- name: Run Django migrations
  django_manage: >
          command={{ item }}
          app_path={{ django_dir }}
          settings=ominicontacto.settings
          virtualenv=/home/freetech/virtualenv
  with_items:
          - migrate
          - "createsuperuser --noinput --username={{ admin_user }} --email=admin@example.com"
          - collectstatic
          - compress
  environment:
    PYTHONPATH: '/home/freetech/ominicontacto:/home/freetech/local'
  ignore_errors: yes
  become: yes
  become_method: sudo
  become_user: freetech

- name: Change password of superuser
  template: "src=templates/changepassword.sh.j2 dest={{ django_dir }}/changepassword.sh mode=0755"

- name: Change password
  shell: "./changepassword.sh chdir={{ django_dir }}"
  environment:
          DJANGO_SETTINGS_MODULE: "ominicontacto.settings"
          PYTHONPATH: '/home/freetech/ominicontacto:/home/freetech/local'




