---

- name: Creation of folder reporte_campana
  file: path=/home/freetech/media_root/reporte_campana state=directory owner=freetech group=freetech recurse=yes

- name: Change owner and group of ominicontacto
  file: "path={{ django_dir }} owner=freetech group=freetech recurse=yes"


- name: Copy of the ominicontacto nginx configuration
  copy: "src={{ django_dir }}/nginx/ominicontacto.conf dest=/etc/nginx/conf.d/ remote_src=yes"

- name: Creation of the nginx server certificate
  set_fact:
          ca_subject: "/C={{ ca_country }}/ST={{ ca_state }}/L={{ ca_locality }}/O={{ ca_organization }}/OU={{ ca_organizationalunit }}/CN={{ omniapp_fqdn }}"

- shell: "openssl req -x509 -nodes -days 1460 -newkey rsa:2048 -keyout server.key -out server.crt -subj \"{{ ca_subject }}\""
  args:
          chdir: /home/freetech/ominicontacto/
  notify: restart nginx

- name: Create the ominicontacto-daemon service
  shell: "{{ item }}"
  with_items:
          - "cp /home/freetech/ominicontacto/ominicontacto-daemon /etc/init.d/"
          - "chmod 755 /etc/init.d/ominicontacto-daemon"
          - "chown root:root /etc/init.d/ominicontacto-daemon"
          - "update-rc.d ominicontacto-daemon defaults"
          - "update-rc.d ominicontacto-daemon enable 2"
          - "update-rc.d ominicontacto-daemon enable 3"
          - "update-rc.d ominicontacto-daemon enable 4"
          - "update-rc.d ominicontacto-daemon enable 5"
  ignore_errors: yes
  notify: restart ominicontacto-daemon

- name: Change the FQDN in config.js
  template: "src=templates/config.js.j2 dest={{ django_dir }}/ominicontacto_app/static/ominicontacto/JS/config.js owner=freetech group=freetech"

