---

- name: Add queuelog trigger to database
  command: psql -U kamailio -w -h 127.0.0.1 -d kamailio -c \'\\i /home/freetech/ominicontacto/ominicontacto_app/sql/plpython/replace_insert_queue_log_ominicontacto_queue_log.sql\'
  become: yes
  become_user: postgres
  become_method: su
