---

- name: Apache adjustments
  shell: "{{ item }}"
  with_items:
      - sed -i 's/\(^upload_max_filesize = \).*/\120M/' /etc/php.ini
      - sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/httpd/conf/httpd.conf
      - sed -i 's/AllowOverride None/AllowOverride All/' /etc/httpd/conf/httpd.conf
  when: asterisk_location == "" and ansible_os_family == "Sangoma"
  become: yes
  become_method: sudo

- name: Creation of asterisk.service
  template: src=templates/asterisk.service dest=/etc/systemd/system/asterisk.service owner=root group=root mode=650

- name: Create simbolic link of asterisk binarie
  file: state=link src={{ asterisk_location }}/sbin/asterisk dest=/usr/sbin/asterisk force=true
  when: asterisk_location != ""
  become: yes
  become_method: sudo

- name: Config of asterisk-freepbx for OML
  file: "state=link src={{ install_prefix }}ominicontacto/ominicontacto_voip/asterisk-files/{{ item }} dest={{ asterisk_location }}/etc/asterisk/{{ item }} force=true owner={{ usuario }} group={{ usuario }}"
  with_items:
      - extensions_custom.conf
      - extensions_fts.conf
      - sip_custom.conf
      - extconfig.conf
      - amd.conf
      - func_odbc.conf
      - cdr_adaptive_odbc.conf
      - http_custom.conf
      - manager_custom.conf
      - queues_custom.conf
      - globals_custom.conf
      - http_custom.conf
      - pjsip.transports_custom.conf
      - res_odbc_custom.conf
  become: yes
  become_method: sudo
  when: asterisk_location == "" or ansible_os_family == "Sangoma"

- name: Config of asterisk for OML
  file: "state=link src={{ install_prefix }}ominicontacto/ominicontacto_voip/asterisk-files/conf/{{ item }} dest={{ asterisk_location }}/etc/asterisk/{{ item }} force=true owner={{ usuario }} group={{ usuario }} mode=755"
  with_items:
      - amd.conf
      - chan_dahdi.conf
      - extconfig.conf
      - extensions.conf
      - features.conf
      - func_odbc.conf
      - http.conf
      - indications.conf
      - logger.conf
      - manager.conf
      - modules.conf
      - musiconhold.conf
      - oml_extensions.conf
      - oml_extensions_sub.conf
      - oml_func_odbc.conf
      - oml_manager.conf
      - oml_res_odbc.conf
      - queues.conf
      - res_odbc.conf
      - sip.conf
      - udptl.conf
  become: yes
  become_method: sudo
  when: asterisk_location != ""

- name: Copy of all asterisk config files
  shell: "cp *.conf {{ asterisk_location }}/etc/asterisk/ chdir={{ install_prefix }}ominicontacto/ominicontacto_voip/asterisk-files/conf/archivos-no-enlaces/"
  when: asterisk_location != ""

- name: Copy of the php agis
  copy: "src={{ install_prefix }}ominicontacto/ominicontacto_voip/asterisk-files/agis/{{ item }} dest={{ asterisk_location }}/var/lib/asterisk/agi-bin/{{ item }} mode=755 remote_src=yes owner={{ usuario }} group={{ usuario }}"
  with_items:
      - omni-asterisk-logout.php
#      - omni-blacklist.php
#      - omni-dialednum.php
      - omni-grabaciones.php
      - phpagi-asmanager.php
      - phpagi.php
  become: yes
  become_method: sudo

- name: Creation of generate_outbound_route_context.php script
  template: "src=templates/agi-bin/generate_outbound_route_context.php dest={{ asterisk_location }}/var/lib/asterisk/agi-bin/generate_outbound_route_context.php mode=755 owner={{ usuario }} group={{ usuario }}"
  become: yes
  become_method: sudo
  when: asterisk_location == ""

- name: Creation of the agis omni-blackist and omni-dialednum
  template: "src=templates/agi-bin/{{ item }} dest={{ asterisk_location }}/var/lib/asterisk/agi-bin/{{ item }} mode=755 owner={{ usuario }} group={{ usuario }}"
  with_items:
      - omni-blacklist.php
      - omni-dialednum.php
  become: yes
  become_method: sudo

- name: Create /usr/local/parselog
  file: dest=/usr/local/parselog state=directory mode=0755 owner={{ usuario }} group={{ usuario }}
  become: yes
  become_method: sudo

- name: Create of update_mix_mixmonitor.pl script
  template: src=templates/update_mix_mixmonitor.pl.j2 dest=/usr/local/parselog/update_mix_mixmonitor.pl mode=755 owner={{ usuario }} group={{ usuario }}
  when: asterisk_location == ""
  become: true
  become_method: sudo

- name: Link the conversor.sh file
  template: src=templates/conversor.sh dest=/usr/local/parselog/conversor.sh owner={{ usuario }} group={{ usuario }} mode=755
  when: asterisk_location != ""

- name: Asterisk crontab modification
  lineinfile: "dest=/var/spool/cron/asterisk line=\"*/5 * * * * root {{ asterisk_location }}/var/lib/asterisk/agi-bin/omni-asterisk-logout.php\""
  when: asterisk_location == ""

- name: Copy the cron-omnileads file
  template: src=templates/cron-omnileads dest=/etc/cron.d/cron-omnileads owner=root group=root
  when: asterisk_location != ""

- name: Link odbc librarie to postgresql libs
  file: state=link src=/usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so dest=/usr/lib/postgresql/9.6/lib/psqlodbcw.so owner=root group=root mode=700
  when: ansible_os_family == "Debian"
  become: true
  become_method: sudo

- name: Creation of odbcinst.ini file
  template: src=templates/etc/odbcinst.ini dest=/etc/odbcinst.ini owner=root group=root mode=700
  become: true
  become_method: sudo

- name: Copy of odbc.ini file and omnileads sounds
  shell: "{{ item }} chdir={{ install_prefix }}ominicontacto/ominicontacto_voip/asterisk-files"
  with_items:
      - cp {{ install_prefix }}ominicontacto/ominicontacto_voip/extra-files/odbc.ini /etc/
      - mkdir {{ asterisk_location }}/var/lib/asterisk/sounds/es
      - mkdir {{ asterisk_location }}/var/lib/asterisk/sounds/en
      - mkdir {{ asterisk_location }}/var/lib/asterisk/sounds/oml
      - tar xzvf sounds/es-oml.tgz -C {{ asterisk_location }}/var/lib/asterisk/sounds/es/
      - tar xzvf sounds/en-oml.tgz -C {{ asterisk_location }}/var/lib/asterisk/sounds/en/
  ignore_errors: yes

- name: Add web enabled in /etc/asterisk/manager.conf
  ini_file: "path={{ asterisk_location }}/etc/asterisk/manager.conf section=general option=webenabled no_extra_spaces=yes value=yes state=present"

- name: Add web nocolor=yes in /etc/asterisk/asterisk.conf
  ini_file: "path={{ asterisk_location }}/etc/asterisk/asterisk.conf section=options option=nocolor no_extra_spaces=yes value=yes state=present"

- name: Change permissions to asterisk user
  file: path={{ item }} owner=asterisk group=asterisk state=directory recurse=yes
  with_items:
      - /etc/asterisk
      - /var/lib/asterisk/agi-bin
      - /usr/local/parselog
  when: asterisk_location == ""

- name: Set up permissions of asterisk
  shell: "{{ item }}"
  with_items:
          - "chown -R {{ usuario }}.{{ usuario }} {{ asterisk_location }}"
  when: asterisk_location != ""
  become: yes
  become_method: sudo

- name: Start and enable asterisk
  command: "{{ item }}"
  with_items:
          - "systemctl daemon-reload"
          - "systemctl enable asterisk"
          - "service asterisk stop"
          - "service asterisk start"
  become: true
  become_method: sudo
  ignore_errors: yes

- name: Start asterisk
  shell: "fwconsole start"
  when: ansible_os_family == "Sangoma" and asterisk_location == ""
  become: yes
  become_method: sudo
  ignore_errors: yes

- name: Reload of asterisk config
  shell: "asterisk -rx 'module reload'"
  tags: postinstall
  become: yes
  become_method: sudo
  ignore_errors: yes

- name: Configuration of logrotate
  template: src=templates/omnileads dest=/etc/logrotate.d/omnileads owner=root group=root mode=644
