# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se crea /opt/omnileads/kamailio directory
- name: Create prefix directory
  file: state=directory path={{ install_prefix }} owner={{ usuario }} group={{ usuario }}

# Se sestean variables de nombre de los targz que se descargan
- set_fact: asterisk_tar=asterisk-13.22.0.tar.gz
- set_fact: jansson_tar=jansson-2.7.tar.gz

# Se descargan los paquetes
- name: Download of asterisk sources
  get_url: "url={{ item }} dest=/usr/src/ timeout=120"
  with_items:
        - "{{ asterisk_v13 }}"
        - "{{ jansson }}"
  become: yes
  become_method: sudo

# Se descomprimen
- name: Untar of sources
  unarchive: "src=/usr/src/{{ item }} dest=/usr/src/ remote_src=yes"
  with_items:
      - "{{ asterisk_tar }}"
      - "{{ jansson_tar }}"
  become: yes
  become_method: sudo

# Se borran
- name: Erase of tar.gz files
  file: "dest=/usr/src/{{ item }} state=absent"
  with_items:
      - "{{ asterisk_tar }}"
      - "{{ jansson_tar }}"
  become: yes
  become_method: sudo

# Se crea el directorio /opt/omnileads/asterisk
- name: Creation of asterisk prefix directory
  file: path={{ install_prefix }}asterisk state=directory owner={{ usuario }} group={{ usuario }}
  become: yes
  become_method: sudo

# Se crea un directorio para jansson
- name: Create jansson directory prefix
  file: path={{ install_prefix }}jansson-2.7 state=directory owner={{ usuario }} group={{ usuario }}
  become: yes
  become_method: sudo

# Pasos para instalar jansson
- name: Jansson installation
  shell: "{{ item }} chdir=/usr/src/jansson-2.7"
  with_items:
          - "autoreconf -i"
          - "./configure --libdir={{ install_prefix }}jansson-2.7/lib64 --prefix={{ install_prefix }}jansson-2.7"
          - "make"
          - "make install"
  become: yes
  become_method: sudo

# Pasos para instalar asterisk  se comienza con el install de prerequisitos y luego con el configure
- name: Asterisk installation (centos)
  shell: "{{ item }} chdir=/usr/src/asterisk-13.22.0"
  with_items:
          - contrib/scripts/install_prereq install
          - ./configure --libdir={{ install_prefix }}asterisk/lib64 --prefix={{ install_prefix }}asterisk --with-pjproject-bundled
  when: ansible_os_family == "RedHat"

# Esta task es necesaria porque en debian hay un paquete que pregunta cual es el countrycode telefonico del pais donde va a estar asterisk instalado
# El debconf sirve para confirugarle predeterminadamente la opcion de 59 (country code argentino) y asi no pida el input
- name: Set country code for libvp1 package
  debconf: name='libvpb0' question='libvpb1/countrycode' value={{ country_code }} vtype='string'
  when: ansible_os_family == "Debian"

- name: Asterisk installation (debian)
  shell: "{{ item }} chdir=/usr/src/asterisk-13.22.0"
  with_items:
          - echo 'y' | contrib/scripts/install_prereq install
          - ./configure --libdir={{ install_prefix }}asterisk/lib64 --prefix={{ install_prefix }}asterisk
  when: ansible_os_family == "Debian"

# Se sigue con el la ejecucion de este script para que permita mp3
- shell: "contrib/scripts/get_mp3_source.sh chdir=/usr/src/asterisk-13.22.0"
  register: command_result
  become: yes
  become_method: sudo
  ignore_errors: yes

# Se hace la instalacion de asterisk
- shell: "{{ item }} chdir=/usr/src/asterisk-13.22.0"
  with_items:
          - make menuselect.makeopts
          - menuselect/menuselect --enable format_mp3 menuselect.makeopts
          - menuselect/menuselect --enable CORE-SOUNDS-EN-WAV menuselect.makeopts
          - menuselect/menuselect --enable CORE-SOUNDS-ES-WAV menuselect.makeopts
          - menuselect/menuselect --enable CORE-SOUNDS-FR-WAV menuselect.makeopts
          - menuselect/menuselect --enable CORE-SOUNDS-IT-WAV menuselect.makeopts
          - menuselect/menuselect --enable CORE-SOUNDS-RU-WAV menuselect.makeopts
          - menuselect/menuselect --enable CORE-SOUNDS-JA-WAV menuselect.makeopts
          - menuselect/menuselect --enable CORE-SOUNDS-SV-WAV menuselect.makeopts
          - menuselect/menuselect --enable EXTRA-SOUNDS-EN-WAV menuselect.makeopts
          - menuselect/menuselect --enable EXTRA-SOUNDS-FR-WAV menuselect.makeopts
          - make
          - make install
          - make config
          - ldconfig
 # become: yes
 # become_method: sudo

# Se mueven los directorios de jansson e iksemel a /opt/omnileads/asterisk -- FIX ME -- hay mejor forma de hacer mv?
- name: Organizing the asterisk directories
  shell: "mv jansson-2.7 asterisk/ chdir={{ install_prefix }}"

# Se borran los paquetes descargados
- name: Erase the downloaded directories of asterisk
  file: path=/usr/src/{{ item }} state=absent
  with_items:
    - asterisk-13.22.0
    - jansson-2.7
