---

#----------------------------------------------------------------------
# Directorios básicos
#----------------------------------------------------------------------

- name: Create the required directories
  file: "dest={{ item }} state=directory owner=freetech mode=0755"
    # /home/freetech es incluido xq el permiso por default (0700) hace que
  with_items:
          - /home/freetech
          - /home/freetech/.pip
          - /home/freetech/ominicontacto/
  sudo: yes
  tags:
          - deploy


#----------------------------------------------------------------------
# pip / virtualenv
#----------------------------------------------------------------------

- name: Setup pip
  ini_file: >
    dest=/home/freetech/.pip/pip.conf
    section=install
    option='download-cache'
    value='/home/freetech/.pip/cache'

- name: Editar el sudoers para ejecutar rsync sin pedir password de sudo
  lineinfile: "dest=/etc/sudoers line=\"freetech ALL = NOPASSWD: /usr/bin/rsync\""

- name: Upload built (rsync to /ominicontacto)
  # Copies xxx/app to /home/freetech/ominicontacto (/ominicontacto on dest is implicit)
  synchronize: "src={{ build_dir }} dest=/home/freetech delete=yes checksum=yes times=no"
  become: yes
  become_method: su
  become_user: freetech


#- name: Copy location of pg_config exceutable to /usr/sbin
#  copy: src=/usr/pgsql-9.6/bin/pg_config dest=/usr/local/sbin/ remote_src=yes
#  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
#- name: Change $PATH of freetech user to add pg_config location
#  lineinfile: "dest=/home/freetech/.bashrc line=\"export PATH=$PATH:/usr/pgsql-9.6/bin/\""
# when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
#  become: yes
#  become_method: su
#  become_user: freetech

- name: Setup virtualenv
  pip: >
    requirements={{ django_dir }}/requeriments.txt
    virtualenv={{ django_dir }}/virtualenv
  when: ansible_os_family == "Debian"

#- name: Setup virtualenv
#  pip:
#    requirements={{ django_dir }}/requeriments.txt
#    virtualenv={{ django_dir }}/virtualenv
#    virtualenv_command=/usr/bin/virtualenv-2.7
#  environment:
#      PATH: /usr/pgsql-9.6/bin/:{{ lookup('env', 'PATH') }}:/home/freetech/ominicontacto/virtualenv/bin
      #PATH: "$PATH:/usr/pgsql-9.6/bin/:/home/freetech/virtualenv/bin"
#  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"


- name: Change owner and group of ominicontacto
  file: "path={{ django_dir }} owner=freetech group=freetech recurse=yes"

- name: Upload oml_settings_local.py
  template: src=templates/oml_settings_local_debian.py dest={{ django_dir }}
  when: ansible_os_family == "Debian"
- shell:  "mv oml_settings_local_debian.py oml_settings_local.py chdir={{ django_dir }}"
  when: ansible_os_family == "Debian"

- name: Upload oml_settings_local.py
  template: src=templates/oml_settings_local_sangoma.py dest={{ django_dir }}
  when: ansible_os_family == "Sangoma"


- shell: "mv oml_settings_local_sangoma.py oml_settings_local.py chdir={{ django_dir }}"
  when: ansible_os_family == "Sangoma"


- name: Upload oml_settings_local.py
  template: src=templates/oml_settings_local_centos.py dest={{ django_dir }}
  when: ansible_os_family == "RedHat"


- shell: "mv oml_settings_local_centos.py oml_settings_local.py chdir={{ django_dir }}"
  when: ansible_os_family == "RedHat"



