---

#----------------------------------------------------------------------
# Directorios básicos
#----------------------------------------------------------------------

- name: Create the required directories
  file: "dest={{ item }} state=directory owner=freetech mode=0755"
    # /home/freetech es incluido xq el permiso por default (0700) hace que
  with_items:
          - /home/freetech
          - /home/freetech/.pip
          - /home/freetech/ominicontacto/
  sudo: yes
  tags:
          - deploy


#----------------------------------------------------------------------
# pip / virtualenv
#----------------------------------------------------------------------

- name: Setup pip
  ini_file: >
    dest=/home/freetech/.pip/pip.conf
    section=install
    option='download-cache'
    value='/home/freetech/.pip/cache'
  tags:
    - virtualenv

- name: Editar el sudoers para ejecutar rsync sin pedir password de sudo
  lineinfile: "dest=/etc/sudoers line=\"freetech ALL = NOPASSWD: /usr/bin/rsync\""

- name: Upload built (rsync to /ominicontacto)
  # Copies xxx/app to /home/freetech/ominicontacto (/ominicontacto on dest is implicit)
  synchronize: "src={{ build_dir }} dest=/home/freetech delete=yes checksum=yes times=no"
  tags:
    - deploy

- name: Setup virtualenv
  pip: >
    requirements={{ django_dir }}/requeriments.txt
    virtualenv={{ django_dir }}/virtualenv
  tags:
    - virtualenv

- name: Upload oml_settings_local.py
  template: src=templates/oml_settings_local.py dest={{ django_dir }} 
  tags:
          - deploy


- include: postgres_users.yml
  when: not post_install


