---

#----------------------------------------------------------------------
# Directorios básicos
#----------------------------------------------------------------------

#- name: Change key permission
#  file: path=/home/freetech/.ssh/ state=directory owner=freetech group=freetech mode=600 recurse=yes

- name: Creation of freetech group
  group: name=freetech state=present

- name: Create freetech user
  user: name=freetech group=freetech shell=/bin/bash state=present

- name: Create the required directories
  file: "dest={{ item }} state=directory owner=freetech group=freetech mode=0755 recurse=yes"
    # /home/freetech es incluido xq el permiso por default (0700) hace que
  with_items:
          - /home/freetech
          - /home/freetech/.pip
          - /home/freetech/ominicontacto/
          - /home/freetech/local
          - /home/freetech/nginx_certs
          - /home/freetech/media_root/reporte_campana
          - /home/freetech/static
          - /home/freetech/log


#----------------------------------------------------------------------
# pip / virtualenv
#----------------------------------------------------------------------

- name: Setup pip
  ini_file: >
    dest=/home/freetech/.pip/pip.conf
    section=install
    option='download-cache'
    value='/home/freetech/.pip/cache'
  become: yes
  become_method: su
  become_user: freetech

- name: Editar el sudoers para ejecutar rsync sin pedir password de sudo
  lineinfile: "dest=/etc/sudoers line=\"freetech ALL = NOPASSWD: /usr/bin/rsync\""

- name: Upload built (rsync to /ominicontacto)
  # Copies xxx/app to /home/freetech/ominicontacto (/ominicontacto on dest is implicit)
  synchronize: "src={{ build_dir }} dest=/home/freetech delete=yes checksum=yes times=no"
  when: desarrollo == 0

- name: Change permissions on id_rsa
  shell: "chmod 700 /home/freetech/.ssh/id_rsa"
  when: ansible_os_family == "RedHat" or ansible_os_family == "Sangoma"

- name: Clone of OML repository
  git: repo=git@bitbucket.org:freetechdesarrollo/ominicontacto.git version={{ rama }} dest=/home/freetech/ominicontacto/
  when: desarrollo != 0
  become: yes
  become_method: su
  become_user: freetech
  ignore_errors: yes

- name: Checkout of desired branch
  shell: "git checkout {{ rama }} chdir=/home/freetech/ominicontacto"
  become: yes
  become_method: su
  become_user: freetech
  when: desarrollo != 0

- name: Change owner and group of ominicontacto
  file: "path={{ django_dir }} owner=freetech group=freetech recurse=yes"

- name: Upgrade of python setuptools
  pip:
    name=setuptools
    virtualenv=/home/freetech/virtualenv
    virtualenv_command=/usr/bin/virtualenv-2.7
    extra_args=--upgrade
  environment:
    PATH: /home/freetech/virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-9.6/bin
    PYTHONPATH: '/home/freetech/ominicontacto:/home/freetech/local'
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  become: yes
  become_method: su
  become_user: freetech

- name: Upgrade of python setuptools
  pip:
    name=setuptools
    virtualenv=/home/freetech/virtualenv
    virtualenv_command=/usr/bin/virtualenv
    extra_args=--upgrade
  environment:
    PATH: /home/freetech/virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-9.6/bin
    PYTHONPATH: '/home/freetech/ominicontacto:/home/freetech/local'
  when: ansible_os_family == "Debian"

- name: Setup virtualenv
  pip: >
    requirements={{ django_dir }}/requeriments.txt
    virtualenv=/home/freetech/virtualenv
  when: ansible_os_family == "Debian"

- name: Setup virtualenv
  pip:
    requirements={{ django_dir }}/requeriments.txt
    virtualenv=/home/freetech/virtualenv
    virtualenv_command=/usr/bin/virtualenv-2.7
  environment:
      #PATH: /usr/pgsql-9.6/bin/:{{ lookup('env', 'PATH') }}:/home/freetech/ominicontacto/virtualenv/bin
      PATH: /home/freetech/virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-9.6/bin
      PYTHONPATH: '/home/freetech/ominicontacto:/home/freetech/local'
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  become: yes
  become_method: su
  become_user: freetech
- meta: clear_host_errors

- name: Upload oml_settings_local.py
  template: src=templates/oml_settings_local_debian.py dest=/home/freetech/local
  when: ansible_os_family == "Debian"
- shell:  "mv oml_settings_local_debian.py oml_settings_local.py chdir=/home/freetech/local"
  when: ansible_os_family == "Debian"

- name: Upload oml_settings_local.py
  template: src=templates/oml_settings_local.py dest=/home/freetech/local
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  become: yes
  become_user: freetech
  become_method: su

- name: Creation of simbolic link of oml_settings_local.py
  file: state=link src=/home/freetech/local/oml_settings_local.py dest=/home/freetech/ominicontacto/oml_settings_local.py owner=freetech force=true
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  become: yes
  become_user: freetech
  become_method: su
  tags: test

- name: Change owner and group of ominicontacto
  file: "path={{ item }} owner=freetech group=freetech recurse=yes"
  with_items:
    - "{{ django_dir }}"
    - "/home/freetech"

