---

#----------------------------------------------------------------------
# Deploy de la app
#
# Tags mas utiles:
#  - virtualenv: setup de virtualenv & requirements
#  - deploy: deploy de la APP (EXCEPTUANDO cambios en otros
#       compoenentes)

#----------------------------------------------------------------------

- include: deploy.yml

- include: postgres_users.yml
  when: not post_install or ansible_os_family == "Debian"