---

- name: Configure postgres to listen on any port
  lineinfile: "dest=/etc/postgresql/9.4/main/postgresql.conf regexp=\"^#listen_\" line=\"listen_addresses='*'\""
- lineinfile: "dest=/etc/postgresql/9.4/main/pg_hba.conf line=\"host    all             all             {{ red_deploy }}            trust\""

- name: Create kamailio postgres user
  become: yes
  become_user: postgres
  postgresql_user: name=kamailio password=kamailiorw role_attr_flags=SUPERUSER
  tags:
          - virtualenv

- postgresql_user: name=kamailioro password=kamailioro role_attr_flags=SUPERUSER
  become: yes
  become_user: postgres
  tags:
          - virtualenv
  notify: restart postgres



