---

- name: Modificacion de default-ssl.conf
  template: "src=templates/default-ssl.conf.j2 dest=/etc/apache2/sites-enabled/default-ssl.conf "

- name: Modificacion de default-ssl.conf
  template: "src=templates/ports.conf.j2 dest=/etc/apache2/ports.conf"
  notify: restart apache2

- name: Copia de los archivos de asterisk
  shell: "{{ item }} chdir=/usr/src/omnileads-AIO/asterisk/"
  with_items:
          - "cp *.conf /etc/asterisk/"
          - "cp omni-grabaciones.php /var/lib/asterisk/agi-bin/"
          - "sed -i 's/host=192.168.1.83/host={{ omniapp_fqdn }}/' /var/lib/asterisk/agi-bin/omni-grabaciones.php"
          - "cp omni-asterisk-logout.php /var/lib/asterisk/agi-bin/"

- name: Modificacion del crontab de asterisk
  lineinfile: "dest=/var/spool/cron/crontabs/asterisk line=\"*/5 * * * * /var/lib/asterisk/agi-bin/omni-asterisk-logout.php\""








 

