---
- name: Install of php56-fpm
  yum: name=php56w-fpm.x86_64 state=present

- name: Modify of php.ini
  lineinfile: dest=/etc/php.ini regexp="^;cgi.fix_pathinfo" line="cgi.fix_pathinfo=0"

- name: Modify of /php-fpm.d/php-fpm.sock
  template: src=templates/www.conf.j2 dest=/etc/php-fpm.d/www.conf

- name: Enable and start of php-fpm service
  shell: "{{ item }}"
  with_items:
      - systemctl start php-fpm
      - systemctl enable php-fpm

- name: Clone of Omnisup repository
  git: repo={{ omnisup_repo }} dest=/home/freetech/Omnisup
  become: yes
  become_user: freetech
  become_method: su

- name: Copy config.php from /doc to /Omnisup
  shell: "mv /home/freetech/Omnisup/doc/config_ex.php /home/freetech/Omnisup/doc/config.php"
- copy: "src=/home/freetech/Omnisup/doc/config.php dest=/home/freetech/Omnisup remote_src=yes"
  become: yes
  become_user: freetech
  become_method: su

- name: Modify of config.js in /static/Js
  shell: "mv /home/freetech/Omnisup/static/Js/config_ex.js /home/freetech/Omnisup/static/Js/config.js"
- template: "src=templates/config.js.j2 dest=/home/freetech/Omnisup/static/Js/config.js"
  become: yes
  become_user: freetech
  become_method: su

- name: Set permissions of required to freetech's user
  file: "dest: {{ item }} state=file owner=freetech group=freetech recurse=yes"
  with_items:
      - /var/run/php-fpm/php-fpm.sock
      - /home/freetech/Omnisup

- name: Creation of /etc/nginx/conf.d/supervision.conf
  template: src=templates/supervision.conf.j2 dest=/etc/nginx/conf.d/supervision.conf




