---

- name: Install modssl and openssl
  yum: name={{ item }} state=present
  with_items:
      - mod_ssl
      - openssl

- name: Generate openssl keys
  shell: "{{ item }} chdir=/root/"
  with_items:
      - openssl genrsa -out ca.key 2048
- set_fact:
      ca_subject: "/C={{ ca_country }}/ST={{ ca_state }}/L={{ ca_locality }}/O={{ ca_organization }}/OU={{ ca_organizationalunit }}/CN={{ omnicentos_fqdn }}"

- name: Creation of httpd certificate
  shell: "{{ item }} chdir=/root/"
  with_items:
      - "openssl req -new -key ca.key -out ca.csr -passout pass:toor123 -subj \"{{ ca_subject }}\""
      - "openssl x509 -req -days 365 -in ca.csr -signkey ca.key -out ca.crt"
      - "cp ca.crt /etc/pki/tls/certs"
      - "cp ca.key /etc/pki/tls/private/ca.key"
      - "cp ca.csr /etc/pki/tls/private/ca.csr"
      - "restorecon -RvF /etc/pki"

- name: Modify of the httpd.conf file
  template: src=templates/ssl.conf.j2 dest=/etc/httpd/conf.d/ssl.conf

- name: restart httpd
  service: name=httpd state=restarted enabled=yes


