---
- name: Reboot of the server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: Wait for the server to finish rebooting
  become: yes
  become_user: root
  local_action: wait_for host="{{ omni_ip }}" delay=15 state=started port={{ ssh_port }} timeout=600
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"