---

- name: Disable Selinux
  command: "{{ item }}"
  with_items:
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/sysconfig/selinux
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/selinux/config

- name: Update/upgrade of centos
  yum: name='*' state=latest update_cache=yes

- name: Install Development tools
  command: "yum -y groupinstall core base \"Development Tools\""

- name: Install of dependencies
  yum: name={{ item }} state=present
  with_items:
       - lynx
       - tftp-server
       - unixODBC
       - mariadb-server
       - mariadb
       - httpd
       - ncurses-devel
       - sendmail
       - sendmail-cf
       - sox
       - newt-devel
       - libxml2-devel
       - libtiff-devel
       - audiofile-devel
       - gtk2-devel
       - subversion
       - kernel-devel
       - git
       - crontabs
       - cronie
       - cronie-anacron
       - wget
       - vim
       - uuid-devel
       - sqlite-devel
       - net-tools
       - gnutls-devel
       - python-devel
       - texinfo

- name: Install php 5.6
  command: "{{ item }}"
  with_items:
      - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  register: command_result
  failed_when: "'transferencia fallida' in command_result.stderr"
- meta: clear_host_errors

- get_url: url=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm dest=/root/ validate_certs=no
- shell: "rpm -Uvh webtatic-release.rpm chdir=/root"
  register: command_result
  failed_when:
    - "'ya está instalado' not in command_result.stderr"
    - "command_result.rc != 0"

- yum: name={{ item }} state=present
  with_items:
      - php56w
      - php56w-pdo
      - php56w-mysql
      - php56w-mbstring
      - php56w-pear
      - php56w-process
      - php56w-xml
      - php56w-opcache
      - php56w-ldap
      - php56w-intl
      - php56w-soap
- meta: clear_host_errors

- name: Install of NodeJS
  shell: "curl -sL https://rpm.nodesource.com/setup_8.x | bash -"
- yum: name=nodejs state=present

- name: Install Console_Getopt
  pear: name=Console_Getopt state=present
- meta: clear_host_errors


