---

- name: Setup of postgresql
  command: "/usr/pgsql-9.6/bin/postgresql96-setup initdb"
  register: command_result
  failed_when:
    - "'is not empty' not in command_result.stdout"
    - "command_result.rc != 0"
  become: yes
  become_method: sudo
  tags: issabel

- name: Start and enable redis and postgres services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
      - postgresql-9.6.service
      - redis
  become: yes
  become_method: sudo
  tags: issabel

