---

- name: Get the hostname of host
  command: hostname
  register: hostname
  changed_when: false

- name: Get the IP address configured in default interface
  shell: default_if=$(ip route show | awk '/^default/ {print $5}'); ifconfig $default_if | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
  register: omni_ip
  changed_when: false
  tags: always

- name: Creation of deploy folders structure
  file: "dest={{ item }} state=directory owner={{ docker_user }} group={{ docker_user }} mode=0755 recurse=yes"
  with_items:
    - "{{ ast_conf_location }}"
    - "{{ ast_agis_location }}"
    - "{{ nginx_location }}/conf.d"
    - "{{ ast_other_location }}"
    - "{{ omniapp_location }}"
    - "{{ efk_location }}"
  when: devenv == 1

- name: Creation of asterisk deploy content
  include: roles/asterisk/tasks/configuration.yml
  when: devenv == 1

- name: Copy certificate and key pair
  copy: src=/var/tmp/ansible/roles/docker/files/certs dest={{ deploy_location }}

- name: Generate docker-compose file and other files form templates
  template: src=roles/{{ item.src }} dest={{ item.dest }} mode=755 owner={{ docker_user }} group={{ docker_user }}
  with_items:
    - { src: docker/files/devenv/docker-compose.yml, dest: "{{ deploy_location }}/docker-compose.yml"}
    - { src: docker/files/devenv/.env, dest: "{{ deploy_location }}/.env"}
    - { src: docker/files/scripts/run_asterisk.sh, dest: "{{ ast_other_location }}/run_asterisk.sh"}
    - { src: docker/files/scripts/run_omniapp.sh, dest: "{{ omniapp_location }}/run_omniapp.sh"}
    - { src: omniapp_second/templates/bin/conversor.sh, dest: "{{ omniapp_location}}/conversor.sh" }
    - { src: omniapp_second/templates/etc/ominicontacto.conf, dest: "{{ nginx_location }}/conf.d"}
    - { src: omniapp_second/templates/etc/nginx.conf.j2, dest: "{{ nginx_location }}/nginx.conf"}
    - { src: docker/files/scripts/mime.types, dest: "{{ nginx_location }}/mime.types"}
  when: devenv == 1

- name: Generate EFK docker-compose file and configuration files
  template: src=roles/docker/files/efk_infra/{{ item.src }} dest={{ item.dest }} mode=755 owner={{ docker_user }} group={{ docker_user }}
  with_items:
    - { src: kibana.conf, dest: "{{ efk_location }}/kibana.conf"}
    - { src: fluent.conf, dest: "{{ efk_location }}/fluent.conf"}
    - { src: logging_stack.yml, dest: "{{ deploy_location }}"}
  when: devenv == 1

# Se crea el archivo kamailio-local, Este archivo contiene las variables que usa el kamailio.cfg
- name: Creation of kamailio-local.cfg file
  template: src=roles/kamailio/templates/etc/kamailio-local.cfg dest={{ repo_location }}/ominicontacto_voip/kamailio-files/ owner={{ docker_user }} group={{ docker_user }}
  when: devenv == 1

- name: Create omnileads-devenv systemd service
  template: src=files/devenv/omnileads-devenv.service mode=644 dest=/etc/systemd/system/
  when: devenv == 1

- name: Enable omnileads-devenv service
  systemd: name=omnileads-devenv enabled=yes daemon_reload=yes
  when: devenv == 1
