# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
---

- name: Create root path of docker omnileads
  file: path={{ docker_root }}/omnileads/ state=directory recurse=yes owner={{ docker_user }} group={{ docker_user }}

- name: Include docker global variables
  include_vars: group_vars/docker_general_vars.yml
  tags: always

- name: Include docker devenv variables
  include_vars: group_vars/docker_devenv_vars.yml
  when: devenv == 1
  tags: ['docker_build','docker_deploy']

- name: Include docker prodenv variables
  include_vars: group_vars/docker_prodenv_vars.yml
  when: prodenv == 1
  tags: ['docker_build','docker_deploy']

- include_tasks: roles/prerequisitos/tasks/checks.yml
  tags: ['never', 'docker_deploy']

- include: build.yml
  tags: docker_build

- include: deploy.yml
  tags: docker_deploy

- name: Change ownership of {{ docker_root }}/omnileads folder
  file: state=directory owner={{ docker_user }} group={{ docker_user }} path={{ docker_root }}/omnileads recurse=yes
