---

- name: Config of asterisk-freepbx for OML
  shell: "{{ item }} chdir=/usr/src/oml-freepbx/asterisk-files"
  with_items:
      - cp *.conf /etc/asterisk/
      - cp *.php /var/lib/asterisk/agi-bin
      - chmod +x /var/lib/asterisk/agi-bin/omni*

- name: Asterisk crontab modification
  lineinfile: "dest=/var/spool/cron/asterisk line=\"*/5 * * * * /var/lib/asterisk/agi-bin/omni-asterisk-logout.php\""

- name: Create /usr/local/parselog
  file: dest=/usr/local/parselog state=directory mode=0755

- name: Set ownership to asterisk user
  shell: "{{ item }} chdir=/usr/src/oml-freepbx/asterisk-files"
  with_items:
      - cp update_mix_mixmonitor.pl /usr/local/parselog
      - chmod +x /usr/local/parselog/update_mix_mixmonitor.pl
      - chown asterisk.asterisk -R /usr/local/parselog
      - cp /usr/src/oml-freepbx/extra-files/odbcinst.ini /etc/
      - cp /usr/src/oml-freepbx/extra-files/odbc.ini /etc/

- name: Add web enabled in /etc/asterisk/manager.conf
  ini_file: "path=/etc/asterisk/manager.conf section=general option=webnenabled no_extra_spaces=yes value=yes state=present"

- name: Install Mysql-python DB module
  pip: name=MySQL-python

- name: Add user of MySQL omnileads
  mysql_user: "name=omnileads host={{ item }} login_user=root password=admin123 priv=\"asterisk.*:ALL,GRANT\""
  with_items:
      - "localhost"
      - "127.0.0.1"