---

- name: Clone of the RTPengine repo
  git: repo={{ rtpengine_repo }} dest=/usr/src/rtpengine
  ignore_errors: yes

- name: Installation of RTPengine
  shell: "make chdir=/usr/src/rtpengine/daemon"
- copy: src=/usr/src/rtpengine/daemon/rtpengine dest=/usr/local/bin remote_src=yes

- name: Modify of the RTPengine kernel module to let it know where is our kernel
  lineinfile: "path=/usr/src/rtpengine/kernel-module/Makefile regexp=\"^KSRC\" line=\"KSRC   ?= /usr/lib/modules/3.10.0-514.26.2.el7.x86_64\""

- name: Installation of RTPengine kernel module
  shell: "{{ item }} chdir=/usr/src/rtpengine/kernel-module"
  with_items:
      - make
      - insmod xt_RTPENGINE.ko

- name: Installation of IPtables extensions
  shell: "make chdir=/usr/src/rtpengine/iptables-extension"
- copy: src=/usr/src/rtpengine/iptables-extension/libxt_RTPENGINE.so dest=/lib64/xtables

- name: Copy of rptengine init script in sysconfig
  copy: src=/usr/src/oml-freepbx/kamailio-files/rtpengine_sysconfig dest=/etc/sysconfig/rtpengine remote_src=yes
- copy: src=/usr/src/oml-freepbx/kamailio-files/rtpengine.service dest=/etc/systemd/system remote_src=yes

- name: Modify of RTPengine sysconfig file
  lineinfile: "path=/etc/sysconfig/rtpengine regexp=\"^OPTIONS=\" line=\"OPTIONS=\"-i {{ omnifreepbx_ip }} -n 127.0.0.1:22222 -m 20000 -M 30000 -L 7 --log-facility=local1\"
\""

- name: Modify of /etc/rsyslog.conf
  lineinfile: "path=/etc/rsyslog.conf line=\"local1.*                                                -/var/log/rtpengine.log
\""

- name: Last changes
  shell: "{{ item }}"
  with_items:
      - touch /var/log/rtpengine.log
      - systemctl restart rsyslog
      - cp rtpengine.service /etc/systemd/system/
      - systemctl enable rtpengine.service
      - mkdir -p /var/spool/rtpengine
      - systemctl start rtpengine

